export enum CMTransformOption {
  TO_PROPERTY = 'TO_PROPERTY',
  TO_MULTILANGUAGE_PROPERTY = 'TO_MULTILANGUAGE_PROPERTY',
  TO_SUBMODEL_ELEMENT_COLLECTION = 'TO_SUBMODEL_ELEMENT_COLLECTION',
  TO_SUBMODEL_ELEMENT_LIST = 'TO_SUBMODEL_ELEMENT_LIST',
}
