export enum AuthRoles {
  'SYSTEM_ADMIN' = 'SYSTEM_ADMIN',
  'ORGA_ADMIN' = 'ORGA_ADMIN',
  'BENUTZER' = 'BENUTZER',
  'FEED_MAPPING_USER' = 'FEED_MAPPING_USER',
  'MARKT_PUBLISHER' = 'MARKT_PUBLISHER',
  'SHELLS_READER' = 'SHELLS_READER',
  'SHELLS_EDITOR' = 'SHELLS_EDITOR',
}
