server.port=8081
basyx.backend=MongoDB
basyx.environment=file:aas
basyx.cors.allowed-origins=*
basyx.cors.allowed-methods=GET,POST,PATCH,DELETE,PUT,OPTIONS,HEAD
basyx.aasrepository.feature.registryintegration=http://aas-registry2:8080
basyx.submodelrepository.feature.registryintegration=http://sm-registry2:8080
basyx.externalurl=https://supplier2-aas-repository.meta-level.de
spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB
spring.data.mongodb.host=mongo2
spring.data.mongodb.database=aas-env
spring.data.mongodb.authentication-database=admin
spring.data.mongodb.username=mongoAdmin
spring.data.mongodb.password=mongoPassword
mqtt.clientId=AAS-Env-Supplier2
mqtt.hostname=${MQTT_HOST:mosquitto2}
mqtt.port=${MQTT_PORT:1883}
basyx.aasrepository.feature.mqtt.enabled=true
basyx.submodelrepository.feature.mqtt.enabled=true
