using AasDesignerAasApi.Settings.Queries.GetViewerSettings;
using AasDesignerApi.Model;
using AasDesignerModel;
using AasShared.Configuration;
using AutoMapper;
using MediatR;
using Microsoft.EntityFrameworkCore;

namespace AasDesignerSystemManagementApi.Settings.Queries.GetViewerSettings;

public class GetViewerSettingsQuery : IRequest<ViewerSettingsDto>
{
    public AppUser AppUser { get; set; } = null!;
    public long InfrastructureId { get; set; }
}

public class GetViewerSettingsHandler : IRequestHandler<GetViewerSettingsQuery, ViewerSettingsDto>
{
    private readonly IApplicationDbContext _context;
    private readonly IMapper _mapper;
    private readonly AppSettings _appSettings;

    public GetViewerSettingsHandler(
        IApplicationDbContext context,
        IMapper mapper,
        AppSettings appSettings
    )
    {
        _context = context;
        _mapper = mapper;
        _appSettings = appSettings;
    }

    public async Task<ViewerSettingsDto> Handle(
        GetViewerSettingsQuery request,
        CancellationToken cancellationToken
    )
    {
        var infrastructure = await _context
            .AasInfrastructureSettings.AsNoTracking()
            .FirstOrDefaultAsync(i => i.Id == request.InfrastructureId, cancellationToken);

        if (infrastructure == null)
        {
            throw new Exception($"Infrastructure with ID {request.InfrastructureId} not found.");
        }

        var currentPat = _context
            .Apikeys.Where(a =>
                a.BenutzerId == request.AppUser.BenutzerId
                && a.OrganisationId == request.AppUser.OrganisationId
                && a.AasInfrastructureSettingsId == request.InfrastructureId
            )
            .FirstOrDefault();

        var personalAccessToken = currentPat?.Key.ToString() ?? string.Empty;
        if (String.IsNullOrWhiteSpace(personalAccessToken))
        {
            // Generieren
            personalAccessToken = Guid.NewGuid().ToString();
            var apikey = new Apikey
            {
                Key = Guid.Parse(personalAccessToken),
                ValidUntil = DateTime.Now.AddYears(1),
                Active = true,
                Notice = "PAT Generated by AAS Designer",
                Scopes = new List<string> { ApiScopes.AASX_READ_API, ApiScopes.AASX_WRITE_API },
                OrganisationId = request.AppUser.OrganisationId,
                AasInfrastructureSettingsId = request.InfrastructureId,
                BenutzerId = request.AppUser.BenutzerId,
            };
            _context.Apikeys.Add(apikey);
            await _context.SaveChangesAsync(cancellationToken);
        }

        return new ViewerSettingsDto
        {
            SmRepoUrl = infrastructure.SubmodelRepositoryUrl,
            AasRepoUrl = infrastructure.AasRepositoryUrl,
            AasRegistryUrl = infrastructure.AasRegistryUrl,
            CdRepoUrl = infrastructure.ConceptDescriptionRepositoryUrl,
            DiscoveryUrl = infrastructure.AasDiscoveryUrl,
            ViewerAppUrl = _appSettings.ViewerAppUrl,
            SmRegistryUrl = infrastructure.SubmodelRegistryUrl,
            PersonalAccessToken = personalAccessToken,
        };
    }
}
