#!/usr/bin/env bash

set -euo pipefail

CURRENT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=../lib/common.sh
source "$CURRENT_DIR/../lib/common.sh"

main() {
  wizard_banner "OSS" "interactive"
  info "Compose Wizard (OSS/Community)"

  local START_ONLY="no"
  if [ "${1-}" = "--start-only" ]; then
    START_ONLY="yes"
    shift
  fi
  if [ $# -gt 0 ]; then
    die "Unbekanntes Argument: $1"
  fi

  STATE_FILE=""
  STATE_FILE="$CURRENT_DIR/../state/oss.defaults.env"
  load_state_file "$STATE_FILE"
  migrate_legacy_frontend_base_urls
  apply_standard_container_ports

  if [ "$START_ONLY" = "yes" ]; then
    local PROJECT_NAME="${PROJECT_NAME-}"
    local STACK_DIR="${STACK_DIR-}"
    local COMPOSE_FILE
    local ENV_FILE
    local IMAGE_SOURCE_CURRENT="${IMAGE_SOURCE-}"
    local DEFAULT_STACK_DIR
    DEFAULT_STACK_DIR="$(default_generated_stack_dir)"
    PROJECT_NAME="${PROJECT_NAME:-aas-suite}"
    STACK_DIR="${STACK_DIR:-$DEFAULT_STACK_DIR}"
    COMPOSE_FILE="$(default_generated_compose_file "$STACK_DIR")"
    ENV_FILE="$(default_generated_env_file "$STACK_DIR")"
    [ -f "$COMPOSE_FILE" ] || die "Compose-Datei nicht gefunden: $COMPOSE_FILE"
    [ -f "$ENV_FILE" ] || die "Env-Datei nicht gefunden: $ENV_FILE"
    prepare_postgres_init_assets "$COMPOSE_FILE"
    info "Starte vorhandenen Stack mit gespeicherten Werten ..."
    docker compose -p "$PROJECT_NAME" --env-file "$ENV_FILE" -f "$COMPOSE_FILE" config >/dev/null
    pull_compose_images "$COMPOSE_FILE" "$ENV_FILE" "$PROJECT_NAME" "$IMAGE_SOURCE_CURRENT"
    docker compose -p "$PROJECT_NAME" --env-file "$ENV_FILE" -f "$COMPOSE_FILE" up -d
    docker compose -p "$PROJECT_NAME" --env-file "$ENV_FILE" -f "$COMPOSE_FILE" ps
    info "Fertig."
    info "Compose: $COMPOSE_FILE"
    info "Env: $ENV_FILE"
    return 0
  fi

  persist_state() {
    save_state_file "$STATE_FILE" \
      PROJECT_NAME STACK_DIR NETWORK_NAME \
      IMAGE_SOURCE \
      DESIGNER_BACKEND_IMAGE_REPO DESIGNER_BACKEND_IMAGE_TAG DESIGNER_BACKEND_CONTAINER_PORT \
      GATEWAY_IMAGE_REPO GATEWAY_IMAGE_TAG GATEWAY_HOST_PORT GATEWAY_CONTAINER_PORT \
      FRONTEND_IMAGE_REPO FRONTEND_IMAGE_TAG FRONTEND_CONTAINER_PORT BASE_URL \
      POSTGRES_IMAGE_REPO POSTGRES_IMAGE_TAG POSTGRES_CONTAINER_PORT \
      POSTGRES_DB POSTGRES_USER POSTGRES_PASSWORD POSTGRES_VOLUME BASYX_POSTGRES_DB KEYCLOAK_POSTGRES_DB \
      KEYCLOAK_MODE KEYCLOAK_CLUSTER_URL KEYCLOAK_ISSUER KEYCLOAK_WELLKNOWN_URL KEYCLOAK_PUBLIC_ISSUER KEYCLOAK_PUBLIC_WELLKNOWN_URL \
      KEYCLOAK_CLIENT_ID KEYCLOAK_AUDIENCE KEYCLOAK_SCOPES KEYCLOAK_RESOURCE_ACCESS_NAME \
      KEYCLOAK_ADMIN_REALM KEYCLOAK_ADMIN_CLIENT_ID KEYCLOAK_ADMIN_CLIENT_SECRET KEYCLOAK_ADMIN_USERNAME KEYCLOAK_ADMIN_PASSWORD \
      INITIAL_ORGANISATION_ADMIN_EMAIL INITIAL_ORGANISATION_ADMIN_NAME INITIAL_ORGANISATION_ADMIN_VORNAME INITIAL_ORGANISATION_ADMIN_PASSWORD \
      SMTP_SERVER SMTP_PORT SMTP_USE_SSL SMTP_USE_TLS SMTP_NEEDS_AUTHENTICATION SENDER_ADDRESS SENDER_USER SENDER_PASSWORD NEW_ORGA_NOTIFICATION_ADDRESS SUBJECT_PREFIX \
      KEYCLOAK_IMAGE_REPO KEYCLOAK_IMAGE_TAG KEYCLOAK_HOST_PORT KEYCLOAK_REALM_FILE KEYCLOAK_THEMES_PATH \
      KEYCLOAK_REALM PUBLIC_GATEWAY_URL \
      BASYX_MODE BASYX_AAS_REPOSITORY_URL BASYX_SUBMODEL_REPOSITORY_URL BASYX_CONCEPT_DESCRIPTION_REPOSITORY_URL BASYX_AAS_REGISTRY_URL BASYX_SUBMODEL_REGISTRY_URL BASYX_AAS_DISCOVERY_URL \
      BASYX_HANDLE_AS_INTERNAL \
      BASYX_AAS_REPOSITORY_CONTAINER BASYX_AAS_REPOSITORY_CONTAINER_PORT BASYX_AAS_REPOSITORY_HC_URL \
      BASYX_SUBMODEL_REPOSITORY_CONTAINER BASYX_SUBMODEL_REPOSITORY_CONTAINER_PORT BASYX_SUBMODEL_REPOSITORY_HC_URL \
      BASYX_CONCEPT_DESCRIPTION_REPOSITORY_CONTAINER BASYX_CONCEPT_DESCRIPTION_REPOSITORY_CONTAINER_PORT BASYX_CONCEPT_DESCRIPTION_REPOSITORY_HC_URL \
      BASYX_AAS_REGISTRY_CONTAINER BASYX_AAS_REGISTRY_CONTAINER_PORT BASYX_AAS_REGISTRY_HC_URL \
      BASYX_SUBMODEL_REGISTRY_CONTAINER BASYX_SUBMODEL_REGISTRY_CONTAINER_PORT BASYX_SUBMODEL_REGISTRY_HC_URL \
      BASYX_AAS_DISCOVERY_CONTAINER BASYX_AAS_DISCOVERY_CONTAINER_PORT BASYX_AAS_DISCOVERY_HC_URL \
      BASYX_REPO_CORS_ALLOWEDORIGINS BASYX_REPO_CORS_ALLOWEDHEADERS BASYX_REPO_CORS_ALLOWEDCREDENTIALS BASYX_REPO_CORS_ALLOWEDMETHODS \
      BASYX_REPO_SERVER_PORT \
      BASYX_REPO_POSTGRES_HOST BASYX_REPO_POSTGRES_PORT BASYX_REPO_POSTGRES_USER BASYX_REPO_POSTGRES_PASSWORD BASYX_REPO_POSTGRES_DBNAME \
      BASYX_REPO_POSTGRES_MAXOPENCONNECTIONS BASYX_REPO_POSTGRES_MAXIDLECONNECTIONS BASYX_REPO_POSTGRES_CONNMAXLIFETIMEMINUTES \
      BASYX_REPO_ABAC_ENABLED BASYX_REPO_ABAC_MODELPATH BASYX_REPO_OIDC_TRUSTLISTPATH BASYX_SMREPO_JWS_PRIVATEKEYPATH \
      AASREG_CORS_ALLOWEDORIGINS AASREG_CORS_ALLOWEDHEADERS AASREG_CORS_ALLOWEDCREDENTIALS AASREG_CORS_ALLOWEDMETHODS \
      AASREG_VIRTUAL_PORT AASREG_SERVER_PORT \
      AASREG_POSTGRES_HOST AASREG_POSTGRES_PORT AASREG_POSTGRES_USER AASREG_POSTGRES_PASSWORD AASREG_POSTGRES_DBNAME \
      AASREG_POSTGRES_MAXOPENCONNECTIONS AASREG_POSTGRES_MAXIDLECONNECTIONS AASREG_POSTGRES_CONNMAXLIFETIMEMINUTES \
      AASREG_ABAC_ENABLED AASREG_ABAC_MODELPATH AASREG_OIDC_TRUSTLISTPATH \
      SMREG_CORS_ALLOWEDORIGINS SMREG_CORS_ALLOWEDHEADERS SMREG_CORS_ALLOWEDCREDENTIALS SMREG_CORS_ALLOWEDMETHODS \
      SMREG_VIRTUAL_PORT SMREG_SERVER_PORT \
      SMREG_POSTGRES_HOST SMREG_POSTGRES_PORT SMREG_POSTGRES_USER SMREG_POSTGRES_PASSWORD SMREG_POSTGRES_DBNAME \
      SMREG_POSTGRES_MAXOPENCONNECTIONS SMREG_POSTGRES_MAXIDLECONNECTIONS SMREG_POSTGRES_CONNMAXLIFETIMEMINUTES \
      SMREG_ABAC_ENABLED SMREG_ABAC_MODELPATH SMREG_OIDC_TRUSTLISTPATH \
      AASDISC_CORS_ALLOWEDORIGINS AASDISC_CORS_ALLOWEDHEADERS AASDISC_CORS_ALLOWEDCREDENTIALS AASDISC_CORS_ALLOWEDMETHODS \
      AASDISC_VIRTUAL_PORT AASDISC_SERVER_PORT \
      AASDISC_POSTGRES_HOST AASDISC_POSTGRES_PORT AASDISC_POSTGRES_USER AASDISC_POSTGRES_PASSWORD AASDISC_POSTGRES_DBNAME \
      AASDISC_POSTGRES_MAXOPENCONNECTIONS AASDISC_POSTGRES_MAXIDLECONNECTIONS AASDISC_POSTGRES_CONNMAXLIFETIMEMINUTES \
      AASDISC_ABAC_ENABLED AASDISC_ABAC_MODELPATH AASDISC_OIDC_TRUSTLISTPATH \
      AAS_REPOSITORY_IMAGE_REPO AAS_REPOSITORY_IMAGE_TAG AAS_REPOSITORY_HOST_PORT \
      SUBMODEL_REPOSITORY_IMAGE_REPO SUBMODEL_REPOSITORY_IMAGE_TAG SUBMODEL_REPOSITORY_HOST_PORT \
      CONCEPT_DESCRIPTION_REPOSITORY_IMAGE_REPO CONCEPT_DESCRIPTION_REPOSITORY_IMAGE_TAG CONCEPT_DESCRIPTION_REPOSITORY_HOST_PORT \
      AAS_REGISTRY_IMAGE_REPO AAS_REGISTRY_IMAGE_TAG AAS_REGISTRY_HOST_PORT \
      SUBMODEL_REGISTRY_IMAGE_REPO SUBMODEL_REGISTRY_IMAGE_TAG SUBMODEL_REGISTRY_HOST_PORT \
      AAS_DISCOVERY_IMAGE_REPO AAS_DISCOVERY_IMAGE_TAG AAS_DISCOVERY_HOST_PORT \
      RUN_CONFIG_CHECK RUN_STACK_START
  }

  handle_interrupt() {
    persist_state
    trap - EXIT
    echo ""
    warn "Abgebrochen. Zwischenstand gespeichert: $STATE_FILE"
    exit 130
  }

  trap persist_state EXIT
  trap handle_interrupt INT TERM

  ask_with_default() {
    prompt_with_default "$@"
    persist_state
  }

  ask_required() {
    prompt_required "$@"
    persist_state
  }

  ask_required_with_default() {
    prompt_required_with_default "$@"
    persist_state
  }

  ask_port() {
    prompt_port "$@"
    persist_state
  }

  ask_choice() {
    prompt_choice "$@"
    persist_state
  }

  local PROJECT_NAME="${PROJECT_NAME-}"
  local STACK_DIR="${STACK_DIR-}"
  local COMPOSE_FILE
  local ENV_FILE
  local NETWORK_NAME="${NETWORK_NAME-}"
  local IMAGE_SOURCE_PREV="${IMAGE_SOURCE-}"
  local IMAGE_SOURCE="${IMAGE_SOURCE-}"
  local DEFAULT_STACK_DIR

  DEFAULT_STACK_DIR="$(default_generated_stack_dir)"

  component_header "Allgemein"
  ask_required_with_default PROJECT_NAME "Projektname" "$(state_default PROJECT_NAME "aas-suite")"
  ask_required_with_default STACK_DIR "Zielordner Stack" "$(state_default STACK_DIR "$DEFAULT_STACK_DIR")"
  ask_required_with_default NETWORK_NAME "Docker Netzwerkname" "$(state_default NETWORK_NAME "aas-network")"
  ask_choice IMAGE_SOURCE "Image-Quelle" "remote,local" "$(state_default IMAGE_SOURCE "remote")"
  COMPOSE_FILE="$(default_generated_compose_file "$STACK_DIR")"
  ENV_FILE="$(default_generated_env_file "$STACK_DIR")"

  local DESIGNER_BACKEND_IMAGE_REPO="${DESIGNER_BACKEND_IMAGE_REPO-}" DESIGNER_BACKEND_IMAGE_TAG="${DESIGNER_BACKEND_IMAGE_TAG-}" DESIGNER_BACKEND_CONTAINER_PORT="${DESIGNER_BACKEND_CONTAINER_PORT-}"
  local GATEWAY_IMAGE_REPO="${GATEWAY_IMAGE_REPO-}" GATEWAY_IMAGE_TAG="${GATEWAY_IMAGE_TAG-}" GATEWAY_HOST_PORT="${GATEWAY_HOST_PORT-}" GATEWAY_CONTAINER_PORT="${GATEWAY_CONTAINER_PORT-}"
  local FRONTEND_IMAGE_REPO="${FRONTEND_IMAGE_REPO-}" FRONTEND_IMAGE_TAG="${FRONTEND_IMAGE_TAG-}" FRONTEND_CONTAINER_PORT="${FRONTEND_CONTAINER_PORT-}"
  local FRONTEND_API_BASE_URL="${FRONTEND_API_BASE_URL-}" FRONTEND_FEEDMAPPING_BASE_URL="${FRONTEND_FEEDMAPPING_BASE_URL-}" BASE_URL="${BASE_URL-}" PUBLIC_GATEWAY_URL="${PUBLIC_GATEWAY_URL-}"
  local POSTGRES_IMAGE_REPO="${POSTGRES_IMAGE_REPO-}" POSTGRES_IMAGE_TAG="${POSTGRES_IMAGE_TAG-}" POSTGRES_CONTAINER_PORT="${POSTGRES_CONTAINER_PORT-}"

  if [ "$IMAGE_SOURCE" != "$IMAGE_SOURCE_PREV" ]; then
    DESIGNER_BACKEND_IMAGE_REPO=""
    DESIGNER_BACKEND_IMAGE_TAG=""
    GATEWAY_IMAGE_REPO=""
    GATEWAY_IMAGE_TAG=""
    FRONTEND_IMAGE_REPO=""
    FRONTEND_IMAGE_TAG=""
  fi

  component_header "Kernservices"
  local DESIGNER_BACKEND_IMAGE_REPO_DEFAULT="gitea.meta-level.de/aas-suite/aas-designer-backend-community"
  local DESIGNER_BACKEND_IMAGE_TAG_DEFAULT="latest"
  local GATEWAY_IMAGE_REPO_DEFAULT="gitea.meta-level.de/aas-suite/aas-designer-gateway"
  local GATEWAY_IMAGE_TAG_DEFAULT="latest"
  local FRONTEND_IMAGE_REPO_DEFAULT="gitea.meta-level.de/aas-suite/aas-designer-frontend-community"
  local FRONTEND_IMAGE_TAG_DEFAULT="latest"
  if [ "$IMAGE_SOURCE" = "local" ]; then
    DESIGNER_BACKEND_IMAGE_REPO_DEFAULT="aas-suite/aas-designer-backend-community"
    DESIGNER_BACKEND_IMAGE_TAG_DEFAULT="local"
    GATEWAY_IMAGE_REPO_DEFAULT="aas-suite/aas-designer-gateway"
    GATEWAY_IMAGE_TAG_DEFAULT="local"
    FRONTEND_IMAGE_REPO_DEFAULT="aas-suite/aas-designer-frontend-community"
    FRONTEND_IMAGE_TAG_DEFAULT="local"
  fi

  ask_required_with_default DESIGNER_BACKEND_IMAGE_REPO "designer-backend Image Repository" "$(state_default DESIGNER_BACKEND_IMAGE_REPO "$DESIGNER_BACKEND_IMAGE_REPO_DEFAULT")"
  ask_required_with_default DESIGNER_BACKEND_IMAGE_TAG "designer-backend Image Tag" "$(state_default DESIGNER_BACKEND_IMAGE_TAG "$DESIGNER_BACKEND_IMAGE_TAG_DEFAULT")"

  ask_required_with_default GATEWAY_IMAGE_REPO "gateway Image Repository" "$(state_default GATEWAY_IMAGE_REPO "$GATEWAY_IMAGE_REPO_DEFAULT")"
  ask_required_with_default GATEWAY_IMAGE_TAG "gateway Image Tag" "$(state_default GATEWAY_IMAGE_TAG "$GATEWAY_IMAGE_TAG_DEFAULT")"
  ask_port GATEWAY_HOST_PORT "gateway Host-Port" "$(state_default GATEWAY_HOST_PORT "8081")"

  ask_required_with_default FRONTEND_IMAGE_REPO "frontend Image Repository" "$(state_default FRONTEND_IMAGE_REPO "$FRONTEND_IMAGE_REPO_DEFAULT")"
  ask_required_with_default FRONTEND_IMAGE_TAG "frontend Image Tag" "$(state_default FRONTEND_IMAGE_TAG "$FRONTEND_IMAGE_TAG_DEFAULT")"
  ask_required_with_default BASE_URL "Gateway / Basis-URL (extern)" "$(state_default BASE_URL "http://localhost:${GATEWAY_HOST_PORT}")"
  migrate_legacy_frontend_base_urls

  component_header "Postgres"
  ask_required_with_default POSTGRES_IMAGE_REPO "postgres Image Repository" "$(state_default POSTGRES_IMAGE_REPO "postgres")"
  ask_required_with_default POSTGRES_IMAGE_TAG "postgres Image Tag" "$(state_default POSTGRES_IMAGE_TAG "16-alpine")"

  local POSTGRES_DB="${POSTGRES_DB-}" POSTGRES_USER="${POSTGRES_USER-}" POSTGRES_PASSWORD="${POSTGRES_PASSWORD-}" POSTGRES_VOLUME="${POSTGRES_VOLUME-}" BASYX_POSTGRES_DB="${BASYX_POSTGRES_DB-}" KEYCLOAK_POSTGRES_DB="${KEYCLOAK_POSTGRES_DB-}"
  ask_required_with_default POSTGRES_DB "Postgres Datenbankname" "$(state_default POSTGRES_DB "aas_designer")"
  ask_required_with_default POSTGRES_USER "Postgres Benutzer" "$(state_default POSTGRES_USER "aas_user")"
  ask_required_with_default POSTGRES_PASSWORD "Postgres Passwort" "$(state_default POSTGRES_PASSWORD "")"
  ask_required_with_default POSTGRES_VOLUME "Postgres Volume-Name" "$(state_default POSTGRES_VOLUME "postgres-data")"
  ask_required_with_default BASYX_POSTGRES_DB "BaSyx Datenbankname (separate DB)" "$(state_default BASYX_POSTGRES_DB "basyx_core")"
  ask_required_with_default KEYCLOAK_POSTGRES_DB "Keycloak Datenbankname (separate DB)" "$(state_default KEYCLOAK_POSTGRES_DB "keycloak")"
  is_db_identifier "$POSTGRES_DB" || die "POSTGRES_DB darf nur Buchstaben, Zahlen und _ enthalten"
  is_db_identifier "$BASYX_POSTGRES_DB" || die "BASYX_POSTGRES_DB darf nur Buchstaben, Zahlen und _ enthalten"
  is_db_identifier "$KEYCLOAK_POSTGRES_DB" || die "KEYCLOAK_POSTGRES_DB darf nur Buchstaben, Zahlen und _ enthalten"

  local KEYCLOAK_MODE="${KEYCLOAK_MODE-}"
  component_header "Keycloak"
  local KEYCLOAK_MODE_DEFAULT
  KEYCLOAK_MODE_DEFAULT="$(state_default KEYCLOAK_MODE "install")"
  ask_choice KEYCLOAK_MODE "Keycloak Modus" "existing,install" "$KEYCLOAK_MODE_DEFAULT"

  local KEYCLOAK_CLUSTER_URL="${KEYCLOAK_CLUSTER_URL-}"
  local KEYCLOAK_ISSUER="${KEYCLOAK_ISSUER-}"
  local KEYCLOAK_WELLKNOWN_URL="${KEYCLOAK_WELLKNOWN_URL-}"
  local KEYCLOAK_PUBLIC_ISSUER="${KEYCLOAK_PUBLIC_ISSUER-}"
  local KEYCLOAK_PUBLIC_WELLKNOWN_URL="${KEYCLOAK_PUBLIC_WELLKNOWN_URL-}"
  local KEYCLOAK_CLIENT_ID="${KEYCLOAK_CLIENT_ID-}"
  local KEYCLOAK_AUDIENCE="${KEYCLOAK_AUDIENCE-}"
  local KEYCLOAK_SCOPES="${KEYCLOAK_SCOPES-}"
  local KEYCLOAK_RESOURCE_ACCESS_NAME="${KEYCLOAK_RESOURCE_ACCESS_NAME-}"
  local KEYCLOAK_ADMIN_REALM="${KEYCLOAK_ADMIN_REALM-}"
  local KEYCLOAK_ADMIN_CLIENT_ID="${KEYCLOAK_ADMIN_CLIENT_ID-}"
  local KEYCLOAK_ADMIN_CLIENT_SECRET="${KEYCLOAK_ADMIN_CLIENT_SECRET-}"
  local KEYCLOAK_ADMIN_USERNAME="${KEYCLOAK_ADMIN_USERNAME-}"
  local KEYCLOAK_ADMIN_PASSWORD="${KEYCLOAK_ADMIN_PASSWORD-}"
  local INITIAL_ORGANISATION_ADMIN_EMAIL="${INITIAL_ORGANISATION_ADMIN_EMAIL-}"
  local INITIAL_ORGANISATION_ADMIN_NAME="${INITIAL_ORGANISATION_ADMIN_NAME-}"
  local INITIAL_ORGANISATION_ADMIN_VORNAME="${INITIAL_ORGANISATION_ADMIN_VORNAME-}"
  local INITIAL_ORGANISATION_ADMIN_PASSWORD="${INITIAL_ORGANISATION_ADMIN_PASSWORD-}"

  local KEYCLOAK_IMAGE_REPO="${KEYCLOAK_IMAGE_REPO-}"
  local KEYCLOAK_IMAGE_TAG="${KEYCLOAK_IMAGE_TAG-}"
  local KEYCLOAK_HOST_PORT="${KEYCLOAK_HOST_PORT-}"
  local KEYCLOAK_REALM_FILE="${KEYCLOAK_REALM_FILE-}"
  local KEYCLOAK_THEMES_PATH="${KEYCLOAK_THEMES_PATH-}"

  if [ "$KEYCLOAK_MODE" = "existing" ]; then
    ask_required_with_default KEYCLOAK_CLUSTER_URL "Keycloak URL aus Gateway-Container (z.B. http://host.docker.internal:8088)" "$(state_default KEYCLOAK_CLUSTER_URL "")"
    ask_required_with_default KEYCLOAK_ISSUER "Keycloak Issuer URL" "$(state_default KEYCLOAK_ISSUER "")"
    ask_required_with_default KEYCLOAK_WELLKNOWN_URL "Keycloak Well-Known URL" "$(state_default KEYCLOAK_WELLKNOWN_URL "")"
    ask_required_with_default KEYCLOAK_PUBLIC_ISSUER "Keycloak Public Issuer URL" "$(state_default KEYCLOAK_PUBLIC_ISSUER "")"
    ask_required_with_default KEYCLOAK_PUBLIC_WELLKNOWN_URL "Keycloak Public Well-Known URL" "$(state_default KEYCLOAK_PUBLIC_WELLKNOWN_URL "")"
    ask_required_with_default KEYCLOAK_CLIENT_ID "Keycloak Client ID" "$(state_default KEYCLOAK_CLIENT_ID "")"
    ask_required_with_default KEYCLOAK_AUDIENCE "Keycloak Audience" "$(state_default KEYCLOAK_AUDIENCE "$KEYCLOAK_CLIENT_ID")"
    ask_required_with_default KEYCLOAK_SCOPES "Keycloak Scopes" "$(state_default KEYCLOAK_SCOPES "openid profile email roles")"
    ask_required_with_default KEYCLOAK_RESOURCE_ACCESS_NAME "Keycloak Resource Access Name" "$(state_default KEYCLOAK_RESOURCE_ACCESS_NAME "$KEYCLOAK_CLIENT_ID")"
    ask_required_with_default KEYCLOAK_ADMIN_REALM "Keycloak Admin Realm" "$(state_default KEYCLOAK_ADMIN_REALM "master")"
    ask_required_with_default KEYCLOAK_ADMIN_CLIENT_ID "Keycloak Admin Client ID" "$(state_default KEYCLOAK_ADMIN_CLIENT_ID "admin-cli")"
    ask_with_default KEYCLOAK_ADMIN_CLIENT_SECRET "Keycloak Admin Client Secret (optional)" "$(state_default KEYCLOAK_ADMIN_CLIENT_SECRET "")"
    ask_required_with_default KEYCLOAK_ADMIN_USERNAME "Keycloak Admin Benutzer" "$(state_default KEYCLOAK_ADMIN_USERNAME "")"
    ask_required_with_default KEYCLOAK_ADMIN_PASSWORD "Keycloak Admin Passwort" "$(state_default KEYCLOAK_ADMIN_PASSWORD "")"
  else
    local KEYCLOAK_REALM="${KEYCLOAK_REALM-}"

    ask_required_with_default KEYCLOAK_IMAGE_REPO "Keycloak Image Repository" "$(state_default KEYCLOAK_IMAGE_REPO "quay.io/keycloak/keycloak")"
    ask_required_with_default KEYCLOAK_IMAGE_TAG "Keycloak Image Tag" "$(state_default KEYCLOAK_IMAGE_TAG "26.0")"
    ask_port KEYCLOAK_HOST_PORT "Keycloak Host-Port" "$(state_default KEYCLOAK_HOST_PORT "8088")"
    ask_required_with_default KEYCLOAK_ADMIN_USERNAME "Keycloak Admin Benutzer" "$(state_default KEYCLOAK_ADMIN_USERNAME "")"
    ask_required_with_default KEYCLOAK_ADMIN_PASSWORD "Keycloak Admin Passwort" "$(state_default KEYCLOAK_ADMIN_PASSWORD "")"
    ask_required_with_default KEYCLOAK_REALM "Keycloak Realm" "$(state_default KEYCLOAK_REALM "aas-local")"
    ask_required_with_default KEYCLOAK_CLIENT_ID "Keycloak Client ID" "$(state_default KEYCLOAK_CLIENT_ID "aas-designer-local")"
    ask_required_with_default KEYCLOAK_AUDIENCE "Keycloak Audience" "$(state_default KEYCLOAK_AUDIENCE "$KEYCLOAK_CLIENT_ID")"
    ask_required_with_default KEYCLOAK_SCOPES "Keycloak Scopes" "$(state_default KEYCLOAK_SCOPES "openid profile email roles")"
    ask_required_with_default KEYCLOAK_RESOURCE_ACCESS_NAME "Keycloak Resource Access Name" "$(state_default KEYCLOAK_RESOURCE_ACCESS_NAME "$KEYCLOAK_CLIENT_ID")"
    ask_required_with_default KEYCLOAK_ADMIN_REALM "Keycloak Admin Realm" "$(state_default KEYCLOAK_ADMIN_REALM "master")"
    ask_required_with_default KEYCLOAK_ADMIN_CLIENT_ID "Keycloak Admin Client ID" "$(state_default KEYCLOAK_ADMIN_CLIENT_ID "admin-cli")"
    ask_with_default KEYCLOAK_ADMIN_CLIENT_SECRET "Keycloak Admin Client Secret (optional)" "$(state_default KEYCLOAK_ADMIN_CLIENT_SECRET "")"
    ask_required_with_default KEYCLOAK_REALM_FILE "Pfad Realm-JSON" "$(state_default KEYCLOAK_REALM_FILE "../stack-assets/keycloak/aas-local-realm.json")"
    ask_required_with_default KEYCLOAK_THEMES_PATH "Pfad Keycloak Themes" "$(state_default KEYCLOAK_THEMES_PATH "../stack-assets/keycloak/themes")"
    local resolved_keycloak_realm_file
    local resolved_keycloak_themes_path
    resolved_keycloak_realm_file="$(resolve_path_from_dir "$CURRENT_DIR" "$KEYCLOAK_REALM_FILE")"
    resolved_keycloak_themes_path="$(resolve_path_from_dir "$CURRENT_DIR" "$KEYCLOAK_THEMES_PATH")"
    [ -f "$resolved_keycloak_realm_file" ] || die "Realm-JSON muss eine existierende Datei sein: $KEYCLOAK_REALM_FILE"
    [ -d "$resolved_keycloak_themes_path" ] || die "Keycloak Themes muss ein existierendes Verzeichnis sein: $KEYCLOAK_THEMES_PATH"

    KEYCLOAK_CLUSTER_URL="http://keycloak:8080"
    KEYCLOAK_ISSUER="http://keycloak:8080/realms/${KEYCLOAK_REALM}"
    KEYCLOAK_WELLKNOWN_URL="${KEYCLOAK_ISSUER}/.well-known/openid-configuration"
    KEYCLOAK_PUBLIC_ISSUER="${PUBLIC_GATEWAY_URL}/realms/${KEYCLOAK_REALM}"
    KEYCLOAK_PUBLIC_WELLKNOWN_URL="${KEYCLOAK_PUBLIC_ISSUER}/.well-known/openid-configuration"
  fi

  component_header "Initialer Benutzer"
  ask_required_with_default INITIAL_ORGANISATION_ADMIN_EMAIL "Initial Admin E-Mail" "$(state_default INITIAL_ORGANISATION_ADMIN_EMAIL "admin@initial.orga")"
  ask_required_with_default INITIAL_ORGANISATION_ADMIN_NAME "Initial Admin Nachname" "$(state_default INITIAL_ORGANISATION_ADMIN_NAME "Admin")"
  ask_required_with_default INITIAL_ORGANISATION_ADMIN_VORNAME "Initial Admin Vorname" "$(state_default INITIAL_ORGANISATION_ADMIN_VORNAME "Demo")"
  ask_required_with_default INITIAL_ORGANISATION_ADMIN_PASSWORD "Initial Admin Passwort" "$(state_default INITIAL_ORGANISATION_ADMIN_PASSWORD "secret-pass")"

  local SMTP_SERVER="${SMTP_SERVER-}"
  local SMTP_PORT="${SMTP_PORT-}"
  local SMTP_USE_SSL="${SMTP_USE_SSL-}"
  local SMTP_USE_TLS="${SMTP_USE_TLS-}"
  local SMTP_NEEDS_AUTHENTICATION="${SMTP_NEEDS_AUTHENTICATION-}"
  local SENDER_ADDRESS="${SENDER_ADDRESS-}"
  local SENDER_USER="${SENDER_USER-}"
  local SENDER_PASSWORD="${SENDER_PASSWORD-}"
  local NEW_ORGA_NOTIFICATION_ADDRESS="${NEW_ORGA_NOTIFICATION_ADDRESS-}"
  local SUBJECT_PREFIX="${SUBJECT_PREFIX-}"

  component_header "Mail"
  ask_required_with_default SMTP_SERVER "SMTP Server" "$(state_default SMTP_SERVER "smtp.company.com")"
  ask_port SMTP_PORT "SMTP Port" "$(state_default SMTP_PORT "587")"
  ask_choice SMTP_USE_SSL "SMTP SSL aktivieren" "true,false" "$(state_default SMTP_USE_SSL "false")"
  ask_choice SMTP_USE_TLS "SMTP TLS aktivieren" "true,false" "$(state_default SMTP_USE_TLS "true")"
  ask_choice SMTP_NEEDS_AUTHENTICATION "SMTP Authentifizierung aktivieren" "true,false" "$(state_default SMTP_NEEDS_AUTHENTICATION "false")"
  ask_required_with_default SENDER_ADDRESS "Absender E-Mail" "$(state_default SENDER_ADDRESS "noreply@company.com")"
  ask_with_default SENDER_USER "SMTP Benutzername" "$(state_default SENDER_USER "")"
  ask_with_default SENDER_PASSWORD "SMTP Passwort" "$(state_default SENDER_PASSWORD "")"
  ask_required_with_default NEW_ORGA_NOTIFICATION_ADDRESS "Benachrichtigungsadresse neue Organisation" "$(state_default NEW_ORGA_NOTIFICATION_ADDRESS "admin@company.com")"
  ask_with_default SUBJECT_PREFIX "Mail Betreff-Präfix" "$(state_default SUBJECT_PREFIX "")"

  local BASYX_MODE="${BASYX_MODE-}"
  local BASYX_MODE_DEFAULT
  BASYX_MODE_DEFAULT="$(state_default BASYX_MODE "install")"
  component_header "BaSyx"
  ask_choice BASYX_MODE "BaSyx Modus" "existing,install" "$BASYX_MODE_DEFAULT"

  local BASYX_AAS_REPOSITORY_URL="${BASYX_AAS_REPOSITORY_URL-}"
  local BASYX_SUBMODEL_REPOSITORY_URL="${BASYX_SUBMODEL_REPOSITORY_URL-}"
  local BASYX_CONCEPT_DESCRIPTION_REPOSITORY_URL="${BASYX_CONCEPT_DESCRIPTION_REPOSITORY_URL-}"
  local BASYX_AAS_REGISTRY_URL="${BASYX_AAS_REGISTRY_URL-}"
  local BASYX_SUBMODEL_REGISTRY_URL="${BASYX_SUBMODEL_REGISTRY_URL-}"
  local BASYX_AAS_DISCOVERY_URL="${BASYX_AAS_DISCOVERY_URL-}"
  local BASYX_REPO_CORS_ALLOWEDORIGINS="${BASYX_REPO_CORS_ALLOWEDORIGINS-}"
  local BASYX_REPO_CORS_ALLOWEDHEADERS="${BASYX_REPO_CORS_ALLOWEDHEADERS-}"
  local BASYX_REPO_CORS_ALLOWEDCREDENTIALS="${BASYX_REPO_CORS_ALLOWEDCREDENTIALS-}"
  local BASYX_REPO_CORS_ALLOWEDMETHODS="${BASYX_REPO_CORS_ALLOWEDMETHODS-}"
  local BASYX_REPO_SERVER_PORT="${BASYX_REPO_SERVER_PORT-}"
  local BASYX_REPO_POSTGRES_HOST="${BASYX_REPO_POSTGRES_HOST-}"
  local BASYX_REPO_POSTGRES_PORT="${BASYX_REPO_POSTGRES_PORT-}"
  local BASYX_REPO_POSTGRES_USER="${BASYX_REPO_POSTGRES_USER-}"
  local BASYX_REPO_POSTGRES_PASSWORD="${BASYX_REPO_POSTGRES_PASSWORD-}"
  local BASYX_REPO_POSTGRES_DBNAME="${BASYX_REPO_POSTGRES_DBNAME-}"
  local BASYX_REPO_POSTGRES_MAXOPENCONNECTIONS="${BASYX_REPO_POSTGRES_MAXOPENCONNECTIONS-}"
  local BASYX_REPO_POSTGRES_MAXIDLECONNECTIONS="${BASYX_REPO_POSTGRES_MAXIDLECONNECTIONS-}"
  local BASYX_REPO_POSTGRES_CONNMAXLIFETIMEMINUTES="${BASYX_REPO_POSTGRES_CONNMAXLIFETIMEMINUTES-}"
  local BASYX_REPO_ABAC_ENABLED="${BASYX_REPO_ABAC_ENABLED-}"
  local BASYX_REPO_ABAC_MODELPATH="${BASYX_REPO_ABAC_MODELPATH-}"
  local BASYX_REPO_OIDC_TRUSTLISTPATH="${BASYX_REPO_OIDC_TRUSTLISTPATH-}"
  local BASYX_SMREPO_JWS_PRIVATEKEYPATH="${BASYX_SMREPO_JWS_PRIVATEKEYPATH-}"
  local AASREG_CORS_ALLOWEDORIGINS="${AASREG_CORS_ALLOWEDORIGINS-}"
  local AASREG_CORS_ALLOWEDHEADERS="${AASREG_CORS_ALLOWEDHEADERS-}"
  local AASREG_CORS_ALLOWEDCREDENTIALS="${AASREG_CORS_ALLOWEDCREDENTIALS-}"
  local AASREG_CORS_ALLOWEDMETHODS="${AASREG_CORS_ALLOWEDMETHODS-}"
  local AASREG_VIRTUAL_PORT="${AASREG_VIRTUAL_PORT-}"
  local AASREG_SERVER_PORT="${AASREG_SERVER_PORT-}"
  local AASREG_POSTGRES_HOST="${AASREG_POSTGRES_HOST-}"
  local AASREG_POSTGRES_PORT="${AASREG_POSTGRES_PORT-}"
  local AASREG_POSTGRES_USER="${AASREG_POSTGRES_USER-}"
  local AASREG_POSTGRES_PASSWORD="${AASREG_POSTGRES_PASSWORD-}"
  local AASREG_POSTGRES_DBNAME="${AASREG_POSTGRES_DBNAME-}"
  local AASREG_POSTGRES_MAXOPENCONNECTIONS="${AASREG_POSTGRES_MAXOPENCONNECTIONS-}"
  local AASREG_POSTGRES_MAXIDLECONNECTIONS="${AASREG_POSTGRES_MAXIDLECONNECTIONS-}"
  local AASREG_POSTGRES_CONNMAXLIFETIMEMINUTES="${AASREG_POSTGRES_CONNMAXLIFETIMEMINUTES-}"
  local AASREG_ABAC_ENABLED="${AASREG_ABAC_ENABLED-}"
  local AASREG_ABAC_MODELPATH="${AASREG_ABAC_MODELPATH-}"
  local AASREG_OIDC_TRUSTLISTPATH="${AASREG_OIDC_TRUSTLISTPATH-}"
  local SMREG_CORS_ALLOWEDORIGINS="${SMREG_CORS_ALLOWEDORIGINS-}"
  local SMREG_CORS_ALLOWEDHEADERS="${SMREG_CORS_ALLOWEDHEADERS-}"
  local SMREG_CORS_ALLOWEDCREDENTIALS="${SMREG_CORS_ALLOWEDCREDENTIALS-}"
  local SMREG_CORS_ALLOWEDMETHODS="${SMREG_CORS_ALLOWEDMETHODS-}"
  local SMREG_VIRTUAL_PORT="${SMREG_VIRTUAL_PORT-}"
  local SMREG_SERVER_PORT="${SMREG_SERVER_PORT-}"
  local SMREG_POSTGRES_HOST="${SMREG_POSTGRES_HOST-}"
  local SMREG_POSTGRES_PORT="${SMREG_POSTGRES_PORT-}"
  local SMREG_POSTGRES_USER="${SMREG_POSTGRES_USER-}"
  local SMREG_POSTGRES_PASSWORD="${SMREG_POSTGRES_PASSWORD-}"
  local SMREG_POSTGRES_DBNAME="${SMREG_POSTGRES_DBNAME-}"
  local SMREG_POSTGRES_MAXOPENCONNECTIONS="${SMREG_POSTGRES_MAXOPENCONNECTIONS-}"
  local SMREG_POSTGRES_MAXIDLECONNECTIONS="${SMREG_POSTGRES_MAXIDLECONNECTIONS-}"
  local SMREG_POSTGRES_CONNMAXLIFETIMEMINUTES="${SMREG_POSTGRES_CONNMAXLIFETIMEMINUTES-}"
  local SMREG_ABAC_ENABLED="${SMREG_ABAC_ENABLED-}"
  local SMREG_ABAC_MODELPATH="${SMREG_ABAC_MODELPATH-}"
  local SMREG_OIDC_TRUSTLISTPATH="${SMREG_OIDC_TRUSTLISTPATH-}"
  local AASDISC_CORS_ALLOWEDORIGINS="${AASDISC_CORS_ALLOWEDORIGINS-}"
  local AASDISC_CORS_ALLOWEDHEADERS="${AASDISC_CORS_ALLOWEDHEADERS-}"
  local AASDISC_CORS_ALLOWEDCREDENTIALS="${AASDISC_CORS_ALLOWEDCREDENTIALS-}"
  local AASDISC_CORS_ALLOWEDMETHODS="${AASDISC_CORS_ALLOWEDMETHODS-}"
  local AASDISC_VIRTUAL_PORT="${AASDISC_VIRTUAL_PORT-}"
  local AASDISC_SERVER_PORT="${AASDISC_SERVER_PORT-}"
  local AASDISC_POSTGRES_HOST="${AASDISC_POSTGRES_HOST-}"
  local AASDISC_POSTGRES_PORT="${AASDISC_POSTGRES_PORT-}"
  local AASDISC_POSTGRES_USER="${AASDISC_POSTGRES_USER-}"
  local AASDISC_POSTGRES_PASSWORD="${AASDISC_POSTGRES_PASSWORD-}"
  local AASDISC_POSTGRES_DBNAME="${AASDISC_POSTGRES_DBNAME-}"
  local AASDISC_POSTGRES_MAXOPENCONNECTIONS="${AASDISC_POSTGRES_MAXOPENCONNECTIONS-}"
  local AASDISC_POSTGRES_MAXIDLECONNECTIONS="${AASDISC_POSTGRES_MAXIDLECONNECTIONS-}"
  local AASDISC_POSTGRES_CONNMAXLIFETIMEMINUTES="${AASDISC_POSTGRES_CONNMAXLIFETIMEMINUTES-}"
  local AASDISC_ABAC_ENABLED="${AASDISC_ABAC_ENABLED-}"
  local AASDISC_ABAC_MODELPATH="${AASDISC_ABAC_MODELPATH-}"
  local AASDISC_OIDC_TRUSTLISTPATH="${AASDISC_OIDC_TRUSTLISTPATH-}"
  BASYX_REPO_POSTGRES_DBNAME="$BASYX_POSTGRES_DB"
  AASREG_POSTGRES_DBNAME="$BASYX_POSTGRES_DB"
  SMREG_POSTGRES_DBNAME="$BASYX_POSTGRES_DB"
  AASDISC_POSTGRES_DBNAME="$BASYX_POSTGRES_DB"

  local AAS_REPOSITORY_IMAGE_REPO="${AAS_REPOSITORY_IMAGE_REPO-}"
  local AAS_REPOSITORY_IMAGE_TAG="${AAS_REPOSITORY_IMAGE_TAG-}"
  local AAS_REPOSITORY_HOST_PORT="${AAS_REPOSITORY_HOST_PORT-}"
  local SUBMODEL_REPOSITORY_IMAGE_REPO="${SUBMODEL_REPOSITORY_IMAGE_REPO-}"
  local SUBMODEL_REPOSITORY_IMAGE_TAG="${SUBMODEL_REPOSITORY_IMAGE_TAG-}"
  local SUBMODEL_REPOSITORY_HOST_PORT="${SUBMODEL_REPOSITORY_HOST_PORT-}"
  local CONCEPT_DESCRIPTION_REPOSITORY_IMAGE_REPO="${CONCEPT_DESCRIPTION_REPOSITORY_IMAGE_REPO-}"
  local CONCEPT_DESCRIPTION_REPOSITORY_IMAGE_TAG="${CONCEPT_DESCRIPTION_REPOSITORY_IMAGE_TAG-}"
  local CONCEPT_DESCRIPTION_REPOSITORY_HOST_PORT="${CONCEPT_DESCRIPTION_REPOSITORY_HOST_PORT-}"
  local AAS_REGISTRY_IMAGE_REPO="${AAS_REGISTRY_IMAGE_REPO-}"
  local AAS_REGISTRY_IMAGE_TAG="${AAS_REGISTRY_IMAGE_TAG-}"
  local AAS_REGISTRY_HOST_PORT="${AAS_REGISTRY_HOST_PORT-}"
  local SUBMODEL_REGISTRY_IMAGE_REPO="${SUBMODEL_REGISTRY_IMAGE_REPO-}"
  local SUBMODEL_REGISTRY_IMAGE_TAG="${SUBMODEL_REGISTRY_IMAGE_TAG-}"
  local SUBMODEL_REGISTRY_HOST_PORT="${SUBMODEL_REGISTRY_HOST_PORT-}"
  local AAS_DISCOVERY_IMAGE_REPO="${AAS_DISCOVERY_IMAGE_REPO-}"
  local AAS_DISCOVERY_IMAGE_TAG="${AAS_DISCOVERY_IMAGE_TAG-}"
  local AAS_DISCOVERY_HOST_PORT="${AAS_DISCOVERY_HOST_PORT-}"
  local BASYX_HANDLE_AS_INTERNAL="${BASYX_HANDLE_AS_INTERNAL-}"
  local BASYX_AAS_REPOSITORY_CONTAINER="${BASYX_AAS_REPOSITORY_CONTAINER-}"
  local BASYX_AAS_REPOSITORY_CONTAINER_PORT="${BASYX_AAS_REPOSITORY_CONTAINER_PORT-}"
  local BASYX_AAS_REPOSITORY_HC_URL="${BASYX_AAS_REPOSITORY_HC_URL-}"
  local BASYX_SUBMODEL_REPOSITORY_CONTAINER="${BASYX_SUBMODEL_REPOSITORY_CONTAINER-}"
  local BASYX_SUBMODEL_REPOSITORY_CONTAINER_PORT="${BASYX_SUBMODEL_REPOSITORY_CONTAINER_PORT-}"
  local BASYX_SUBMODEL_REPOSITORY_HC_URL="${BASYX_SUBMODEL_REPOSITORY_HC_URL-}"
  local BASYX_CONCEPT_DESCRIPTION_REPOSITORY_CONTAINER="${BASYX_CONCEPT_DESCRIPTION_REPOSITORY_CONTAINER-}"
  local BASYX_CONCEPT_DESCRIPTION_REPOSITORY_CONTAINER_PORT="${BASYX_CONCEPT_DESCRIPTION_REPOSITORY_CONTAINER_PORT-}"
  local BASYX_CONCEPT_DESCRIPTION_REPOSITORY_HC_URL="${BASYX_CONCEPT_DESCRIPTION_REPOSITORY_HC_URL-}"
  local BASYX_AAS_REGISTRY_CONTAINER="${BASYX_AAS_REGISTRY_CONTAINER-}"
  local BASYX_AAS_REGISTRY_CONTAINER_PORT="${BASYX_AAS_REGISTRY_CONTAINER_PORT-}"
  local BASYX_AAS_REGISTRY_HC_URL="${BASYX_AAS_REGISTRY_HC_URL-}"
  local BASYX_SUBMODEL_REGISTRY_CONTAINER="${BASYX_SUBMODEL_REGISTRY_CONTAINER-}"
  local BASYX_SUBMODEL_REGISTRY_CONTAINER_PORT="${BASYX_SUBMODEL_REGISTRY_CONTAINER_PORT-}"
  local BASYX_SUBMODEL_REGISTRY_HC_URL="${BASYX_SUBMODEL_REGISTRY_HC_URL-}"
  local BASYX_AAS_DISCOVERY_CONTAINER="${BASYX_AAS_DISCOVERY_CONTAINER-}"
  local BASYX_AAS_DISCOVERY_CONTAINER_PORT="${BASYX_AAS_DISCOVERY_CONTAINER_PORT-}"
  local BASYX_AAS_DISCOVERY_HC_URL="${BASYX_AAS_DISCOVERY_HC_URL-}"
  if [ "$BASYX_MODE" = "existing" ]; then
    BASYX_HANDLE_AS_INTERNAL="false"
    AAS_REPOSITORY_IMAGE_TAG="$(state_default AAS_REPOSITORY_IMAGE_TAG "-")"
    SUBMODEL_REPOSITORY_IMAGE_TAG="$(state_default SUBMODEL_REPOSITORY_IMAGE_TAG "-")"
    CONCEPT_DESCRIPTION_REPOSITORY_IMAGE_TAG="$(state_default CONCEPT_DESCRIPTION_REPOSITORY_IMAGE_TAG "-")"
    AAS_REGISTRY_IMAGE_TAG="$(state_default AAS_REGISTRY_IMAGE_TAG "-")"
    SUBMODEL_REGISTRY_IMAGE_TAG="$(state_default SUBMODEL_REGISTRY_IMAGE_TAG "-")"
    AAS_DISCOVERY_IMAGE_TAG="$(state_default AAS_DISCOVERY_IMAGE_TAG "-")"
    ask_required_with_default BASYX_AAS_REPOSITORY_URL "BaSyx AAS Repository URL" "$(state_default BASYX_AAS_REPOSITORY_URL "")"
    ask_required_with_default BASYX_SUBMODEL_REPOSITORY_URL "BaSyx Submodel Repository URL" "$(state_default BASYX_SUBMODEL_REPOSITORY_URL "")"
    ask_required_with_default BASYX_CONCEPT_DESCRIPTION_REPOSITORY_URL "BaSyx Concept Description Repository URL" "$(state_default BASYX_CONCEPT_DESCRIPTION_REPOSITORY_URL "")"
    ask_required_with_default BASYX_AAS_REGISTRY_URL "BaSyx AAS Registry URL" "$(state_default BASYX_AAS_REGISTRY_URL "")"
    ask_required_with_default BASYX_SUBMODEL_REGISTRY_URL "BaSyx Submodel Registry URL" "$(state_default BASYX_SUBMODEL_REGISTRY_URL "")"
    ask_required_with_default BASYX_AAS_DISCOVERY_URL "BaSyx AAS Discovery URL" "$(state_default BASYX_AAS_DISCOVERY_URL "")"
  elif [ "$BASYX_MODE" = "install" ]; then
    BASYX_HANDLE_AS_INTERNAL="true"
    local SUBMODEL_REPOSITORY_IMAGE_TAG_DEFAULT
    local CONCEPT_DESCRIPTION_REPOSITORY_IMAGE_TAG_DEFAULT
    local AAS_REGISTRY_IMAGE_TAG_DEFAULT
    local SUBMODEL_REGISTRY_IMAGE_TAG_DEFAULT
    local AAS_DISCOVERY_IMAGE_TAG_DEFAULT
    SUBMODEL_REPOSITORY_IMAGE_TAG_DEFAULT="$(state_default SUBMODEL_REPOSITORY_IMAGE_TAG "1.0.0")"
    CONCEPT_DESCRIPTION_REPOSITORY_IMAGE_TAG_DEFAULT="$(state_default CONCEPT_DESCRIPTION_REPOSITORY_IMAGE_TAG "1.0.0")"
    AAS_REGISTRY_IMAGE_TAG_DEFAULT="$(state_default AAS_REGISTRY_IMAGE_TAG "1.0.0")"
    SUBMODEL_REGISTRY_IMAGE_TAG_DEFAULT="$(state_default SUBMODEL_REGISTRY_IMAGE_TAG "1.0.0")"
    AAS_DISCOVERY_IMAGE_TAG_DEFAULT="$(state_default AAS_DISCOVERY_IMAGE_TAG "1.0.0")"

    component_header "BaSyx: aasrepository-go"
    ask_required_with_default AAS_REPOSITORY_IMAGE_REPO "aasrepository-go Image Repository" "$(state_default AAS_REPOSITORY_IMAGE_REPO "eclipsebasyx/aasrepository-go")"
    ask_required_with_default AAS_REPOSITORY_IMAGE_TAG "aasrepository-go Image Tag" "$(state_default AAS_REPOSITORY_IMAGE_TAG "1.0.0")"
    ask_port AAS_REPOSITORY_HOST_PORT "aasrepository-go Host-Port" "$(state_default AAS_REPOSITORY_HOST_PORT "5081")"
    component_header "BaSyx: Shared Defaults"
    ask_required_with_default BASYX_REPO_CORS_ALLOWEDORIGINS "BaSyx CORS_ALLOWEDORIGINS" "$(state_default BASYX_REPO_CORS_ALLOWEDORIGINS "${AASREPO_CORS_ALLOWEDORIGINS-*}")"
    ask_required_with_default BASYX_REPO_CORS_ALLOWEDHEADERS "BaSyx CORS_ALLOWEDHEADERS" "$(state_default BASYX_REPO_CORS_ALLOWEDHEADERS "${AASREPO_CORS_ALLOWEDHEADERS-*}")"
    ask_required_with_default BASYX_REPO_CORS_ALLOWEDCREDENTIALS "BaSyx CORS_ALLOWEDCREDENTIALS" "$(state_default BASYX_REPO_CORS_ALLOWEDCREDENTIALS "${AASREPO_CORS_ALLOWEDCREDENTIALS-true}")"
    ask_required_with_default BASYX_REPO_CORS_ALLOWEDMETHODS "BaSyx CORS_ALLOWEDMETHODS" "$(state_default BASYX_REPO_CORS_ALLOWEDMETHODS "${AASREPO_CORS_ALLOWEDMETHODS-GET,POST,PUT,PATCH,DELETE,OPTIONS}")"
    ask_required_with_default BASYX_REPO_SERVER_PORT "Repository SERVER_PORT" "$(state_default BASYX_REPO_SERVER_PORT "${AASREPO_SERVER_PORT-8080}")"
    ask_required_with_default BASYX_REPO_POSTGRES_HOST "BaSyx POSTGRES_HOST" "$(state_default BASYX_REPO_POSTGRES_HOST "${AASREPO_POSTGRES_HOST-postgres}")"
    ask_required_with_default BASYX_REPO_POSTGRES_PORT "BaSyx POSTGRES_PORT" "$(state_default BASYX_REPO_POSTGRES_PORT "${AASREPO_POSTGRES_PORT-5432}")"
    ask_required_with_default BASYX_REPO_POSTGRES_USER "BaSyx POSTGRES_USER" "$(state_default BASYX_REPO_POSTGRES_USER "${AASREPO_POSTGRES_USER-$POSTGRES_USER}")"
    ask_required_with_default BASYX_REPO_POSTGRES_PASSWORD "BaSyx POSTGRES_PASSWORD" "$(state_default BASYX_REPO_POSTGRES_PASSWORD "${AASREPO_POSTGRES_PASSWORD-$POSTGRES_PASSWORD}")"
    ask_required_with_default BASYX_REPO_POSTGRES_MAXOPENCONNECTIONS "BaSyx POSTGRES_MAXOPENCONNECTIONS" "$(state_default BASYX_REPO_POSTGRES_MAXOPENCONNECTIONS "${AASREPO_POSTGRES_MAXOPENCONNECTIONS-500}")"
    ask_required_with_default BASYX_REPO_POSTGRES_MAXIDLECONNECTIONS "BaSyx POSTGRES_MAXIDLECONNECTIONS" "$(state_default BASYX_REPO_POSTGRES_MAXIDLECONNECTIONS "${AASREPO_POSTGRES_MAXIDLECONNECTIONS-500}")"
    ask_required_with_default BASYX_REPO_POSTGRES_CONNMAXLIFETIMEMINUTES "BaSyx POSTGRES_CONNMAXLIFETIMEMINUTES" "$(state_default BASYX_REPO_POSTGRES_CONNMAXLIFETIMEMINUTES "${AASREPO_POSTGRES_CONNMAXLIFETIMEMINUTES-5}")"
    ask_required_with_default BASYX_REPO_ABAC_ENABLED "BaSyx ABAC_ENABLED" "$(state_default BASYX_REPO_ABAC_ENABLED "${AASREPO_ABAC_ENABLED-false}")"
    ask_required_with_default BASYX_REPO_ABAC_MODELPATH "BaSyx ABAC_MODELPATH" "$(state_default BASYX_REPO_ABAC_MODELPATH "${AASREPO_ABAC_MODELPATH-/security_env/access-rules.json}")"
    ask_required_with_default BASYX_REPO_OIDC_TRUSTLISTPATH "BaSyx OIDC_TRUSTLISTPATH" "$(state_default BASYX_REPO_OIDC_TRUSTLISTPATH "${AASREPO_OIDC_TRUSTLISTPATH-/security_env/trustlist.json}")"
    ask_with_default BASYX_SMREPO_JWS_PRIVATEKEYPATH "Submodel Repository JWS_PRIVATEKEYPATH (optional)" "$(state_default BASYX_SMREPO_JWS_PRIVATEKEYPATH "${SMREPO_JWS_PRIVATEKEYPATH-}")"
    BASYX_AAS_REPOSITORY_CONTAINER="${PROJECT_NAME}-aasrepository-go"
    BASYX_AAS_REPOSITORY_CONTAINER_PORT="${BASYX_REPO_SERVER_PORT}"
    BASYX_AAS_REPOSITORY_URL="http://${BASYX_AAS_REPOSITORY_CONTAINER}:${BASYX_AAS_REPOSITORY_CONTAINER_PORT}"
    BASYX_AAS_REPOSITORY_HC_URL="${BASYX_AAS_REPOSITORY_URL}/health"

    component_header "BaSyx: submodelrepository-go"
    ask_required_with_default SUBMODEL_REPOSITORY_IMAGE_REPO "submodelrepository-go Image Repository" "$(state_default SUBMODEL_REPOSITORY_IMAGE_REPO "eclipsebasyx/submodelrepository-go")"
    ask_required_with_default SUBMODEL_REPOSITORY_IMAGE_TAG "submodelrepository-go Image Tag" "$SUBMODEL_REPOSITORY_IMAGE_TAG_DEFAULT"
    ask_port SUBMODEL_REPOSITORY_HOST_PORT "submodelrepository-go Host-Port" "$(state_default SUBMODEL_REPOSITORY_HOST_PORT "5085")"
    BASYX_SUBMODEL_REPOSITORY_CONTAINER="${PROJECT_NAME}-submodelrepository-go"
    BASYX_SUBMODEL_REPOSITORY_CONTAINER_PORT="${BASYX_REPO_SERVER_PORT}"
    BASYX_SUBMODEL_REPOSITORY_URL="http://${BASYX_SUBMODEL_REPOSITORY_CONTAINER}:${BASYX_SUBMODEL_REPOSITORY_CONTAINER_PORT}"
    BASYX_SUBMODEL_REPOSITORY_HC_URL="${BASYX_SUBMODEL_REPOSITORY_URL}/health"

    component_header "BaSyx: conceptdescriptionrepository-go"
    ask_required_with_default CONCEPT_DESCRIPTION_REPOSITORY_IMAGE_REPO "conceptdescriptionrepository-go Image Repository" "$(state_default CONCEPT_DESCRIPTION_REPOSITORY_IMAGE_REPO "eclipsebasyx/conceptdescriptionrepository-go")"
    ask_required_with_default CONCEPT_DESCRIPTION_REPOSITORY_IMAGE_TAG "conceptdescriptionrepository-go Image Tag" "$CONCEPT_DESCRIPTION_REPOSITORY_IMAGE_TAG_DEFAULT"
    ask_port CONCEPT_DESCRIPTION_REPOSITORY_HOST_PORT "conceptdescriptionrepository-go Host-Port" "$(state_default CONCEPT_DESCRIPTION_REPOSITORY_HOST_PORT "5086")"
    BASYX_CONCEPT_DESCRIPTION_REPOSITORY_CONTAINER="${PROJECT_NAME}-conceptdescriptionrepository-go"
    BASYX_CONCEPT_DESCRIPTION_REPOSITORY_CONTAINER_PORT="${BASYX_REPO_SERVER_PORT}"
    BASYX_CONCEPT_DESCRIPTION_REPOSITORY_URL="http://${BASYX_CONCEPT_DESCRIPTION_REPOSITORY_CONTAINER}:${BASYX_CONCEPT_DESCRIPTION_REPOSITORY_CONTAINER_PORT}"
    BASYX_CONCEPT_DESCRIPTION_REPOSITORY_HC_URL="${BASYX_CONCEPT_DESCRIPTION_REPOSITORY_URL}/health"

    AASREPO_CORS_ALLOWEDORIGINS="$BASYX_REPO_CORS_ALLOWEDORIGINS"
    AASREPO_CORS_ALLOWEDHEADERS="$BASYX_REPO_CORS_ALLOWEDHEADERS"
    AASREPO_CORS_ALLOWEDCREDENTIALS="$BASYX_REPO_CORS_ALLOWEDCREDENTIALS"
    AASREPO_CORS_ALLOWEDMETHODS="$BASYX_REPO_CORS_ALLOWEDMETHODS"
    AASREPO_SERVER_PORT="$BASYX_REPO_SERVER_PORT"
    AASREPO_POSTGRES_HOST="$BASYX_REPO_POSTGRES_HOST"
    AASREPO_POSTGRES_PORT="$BASYX_REPO_POSTGRES_PORT"
    AASREPO_POSTGRES_USER="$BASYX_REPO_POSTGRES_USER"
    AASREPO_POSTGRES_PASSWORD="$BASYX_REPO_POSTGRES_PASSWORD"
    AASREPO_POSTGRES_DBNAME="$BASYX_REPO_POSTGRES_DBNAME"
    AASREPO_POSTGRES_MAXOPENCONNECTIONS="$BASYX_REPO_POSTGRES_MAXOPENCONNECTIONS"
    AASREPO_POSTGRES_MAXIDLECONNECTIONS="$BASYX_REPO_POSTGRES_MAXIDLECONNECTIONS"
    AASREPO_POSTGRES_CONNMAXLIFETIMEMINUTES="$BASYX_REPO_POSTGRES_CONNMAXLIFETIMEMINUTES"
    AASREPO_ABAC_ENABLED="$BASYX_REPO_ABAC_ENABLED"
    AASREPO_ABAC_MODELPATH="$BASYX_REPO_ABAC_MODELPATH"
    AASREPO_OIDC_TRUSTLISTPATH="$BASYX_REPO_OIDC_TRUSTLISTPATH"
    SMREPO_CORS_ALLOWEDORIGINS="$BASYX_REPO_CORS_ALLOWEDORIGINS"
    SMREPO_CORS_ALLOWEDHEADERS="$BASYX_REPO_CORS_ALLOWEDHEADERS"
    SMREPO_CORS_ALLOWEDCREDENTIALS="$BASYX_REPO_CORS_ALLOWEDCREDENTIALS"
    SMREPO_CORS_ALLOWEDMETHODS="$BASYX_REPO_CORS_ALLOWEDMETHODS"
    SMREPO_SERVER_PORT="$BASYX_REPO_SERVER_PORT"
    SMREPO_POSTGRES_HOST="$BASYX_REPO_POSTGRES_HOST"
    SMREPO_POSTGRES_PORT="$BASYX_REPO_POSTGRES_PORT"
    SMREPO_POSTGRES_USER="$BASYX_REPO_POSTGRES_USER"
    SMREPO_POSTGRES_PASSWORD="$BASYX_REPO_POSTGRES_PASSWORD"
    SMREPO_POSTGRES_DBNAME="$BASYX_REPO_POSTGRES_DBNAME"
    SMREPO_POSTGRES_MAXOPENCONNECTIONS="$BASYX_REPO_POSTGRES_MAXOPENCONNECTIONS"
    SMREPO_POSTGRES_MAXIDLECONNECTIONS="$BASYX_REPO_POSTGRES_MAXIDLECONNECTIONS"
    SMREPO_POSTGRES_CONNMAXLIFETIMEMINUTES="$BASYX_REPO_POSTGRES_CONNMAXLIFETIMEMINUTES"
    SMREPO_ABAC_ENABLED="$BASYX_REPO_ABAC_ENABLED"
    SMREPO_ABAC_MODELPATH="$BASYX_REPO_ABAC_MODELPATH"
    SMREPO_OIDC_TRUSTLISTPATH="$BASYX_REPO_OIDC_TRUSTLISTPATH"
    SMREPO_JWS_PRIVATEKEYPATH="$BASYX_SMREPO_JWS_PRIVATEKEYPATH"
    CDREPO_CORS_ALLOWEDORIGINS="$BASYX_REPO_CORS_ALLOWEDORIGINS"
    CDREPO_CORS_ALLOWEDHEADERS="$BASYX_REPO_CORS_ALLOWEDHEADERS"
    CDREPO_CORS_ALLOWEDCREDENTIALS="$BASYX_REPO_CORS_ALLOWEDCREDENTIALS"
    CDREPO_CORS_ALLOWEDMETHODS="$BASYX_REPO_CORS_ALLOWEDMETHODS"
    CDREPO_SERVER_PORT="$BASYX_REPO_SERVER_PORT"
    CDREPO_POSTGRES_HOST="$BASYX_REPO_POSTGRES_HOST"
    CDREPO_POSTGRES_PORT="$BASYX_REPO_POSTGRES_PORT"
    CDREPO_POSTGRES_USER="$BASYX_REPO_POSTGRES_USER"
    CDREPO_POSTGRES_PASSWORD="$BASYX_REPO_POSTGRES_PASSWORD"
    CDREPO_POSTGRES_DBNAME="$BASYX_REPO_POSTGRES_DBNAME"
    CDREPO_POSTGRES_MAXOPENCONNECTIONS="$BASYX_REPO_POSTGRES_MAXOPENCONNECTIONS"
    CDREPO_POSTGRES_MAXIDLECONNECTIONS="$BASYX_REPO_POSTGRES_MAXIDLECONNECTIONS"
    CDREPO_POSTGRES_CONNMAXLIFETIMEMINUTES="$BASYX_REPO_POSTGRES_CONNMAXLIFETIMEMINUTES"
    CDREPO_ABAC_ENABLED="$BASYX_REPO_ABAC_ENABLED"
    CDREPO_ABAC_MODELPATH="$BASYX_REPO_ABAC_MODELPATH"
    CDREPO_OIDC_TRUSTLISTPATH="$BASYX_REPO_OIDC_TRUSTLISTPATH"

    component_header "BaSyx: aasregistry-go"
    ask_required_with_default AAS_REGISTRY_IMAGE_REPO "aasregistry-go Image Repository" "$(state_default AAS_REGISTRY_IMAGE_REPO "eclipsebasyx/aasregistry-go")"
    ask_required_with_default AAS_REGISTRY_IMAGE_TAG "aasregistry-go Image Tag" "$AAS_REGISTRY_IMAGE_TAG_DEFAULT"
    ask_port AAS_REGISTRY_HOST_PORT "aasregistry-go Host-Port" "$(state_default AAS_REGISTRY_HOST_PORT "5082")"
    ask_required_with_default AASREG_SERVER_PORT "aasregistry-go SERVER_PORT" "$(state_default AASREG_SERVER_PORT "8082")"
    ask_required_with_default AASREG_VIRTUAL_PORT "aasregistry-go VIRTUAL_PORT" "$(state_default AASREG_VIRTUAL_PORT "$AASREG_SERVER_PORT")"

    component_header "BaSyx: submodelregistry-go"
    ask_required_with_default SUBMODEL_REGISTRY_IMAGE_REPO "submodelregistry-go Image Repository" "$(state_default SUBMODEL_REGISTRY_IMAGE_REPO "eclipsebasyx/submodelregistry-go")"
    ask_required_with_default SUBMODEL_REGISTRY_IMAGE_TAG "submodelregistry-go Image Tag" "$SUBMODEL_REGISTRY_IMAGE_TAG_DEFAULT"
    ask_port SUBMODEL_REGISTRY_HOST_PORT "submodelregistry-go Host-Port" "$(state_default SUBMODEL_REGISTRY_HOST_PORT "5083")"
    ask_required_with_default SMREG_SERVER_PORT "submodelregistry-go SERVER_PORT" "$(state_default SMREG_SERVER_PORT "8083")"
    ask_required_with_default SMREG_VIRTUAL_PORT "submodelregistry-go VIRTUAL_PORT" "$(state_default SMREG_VIRTUAL_PORT "$SMREG_SERVER_PORT")"

    component_header "BaSyx: aasdiscovery-go"
    ask_required_with_default AAS_DISCOVERY_IMAGE_REPO "aasdiscovery-go Image Repository" "$(state_default AAS_DISCOVERY_IMAGE_REPO "eclipsebasyx/aasdiscovery-go")"
    ask_required_with_default AAS_DISCOVERY_IMAGE_TAG "aasdiscovery-go Image Tag" "$AAS_DISCOVERY_IMAGE_TAG_DEFAULT"
    ask_port AAS_DISCOVERY_HOST_PORT "aasdiscovery-go Host-Port" "$(state_default AAS_DISCOVERY_HOST_PORT "5084")"
    ask_required_with_default AASDISC_SERVER_PORT "aasdiscovery-go SERVER_PORT" "$(state_default AASDISC_SERVER_PORT "8081")"
    ask_required_with_default AASDISC_VIRTUAL_PORT "aasdiscovery-go VIRTUAL_PORT" "$(state_default AASDISC_VIRTUAL_PORT "$AASDISC_SERVER_PORT")"
    AASREG_CORS_ALLOWEDORIGINS="$BASYX_REPO_CORS_ALLOWEDORIGINS"
    AASREG_CORS_ALLOWEDHEADERS="$BASYX_REPO_CORS_ALLOWEDHEADERS"
    AASREG_CORS_ALLOWEDCREDENTIALS="$BASYX_REPO_CORS_ALLOWEDCREDENTIALS"
    AASREG_CORS_ALLOWEDMETHODS="$BASYX_REPO_CORS_ALLOWEDMETHODS"
    AASREG_POSTGRES_HOST="$BASYX_REPO_POSTGRES_HOST"
    AASREG_POSTGRES_PORT="$BASYX_REPO_POSTGRES_PORT"
    AASREG_POSTGRES_USER="$BASYX_REPO_POSTGRES_USER"
    AASREG_POSTGRES_PASSWORD="$BASYX_REPO_POSTGRES_PASSWORD"
    AASREG_POSTGRES_DBNAME="$BASYX_REPO_POSTGRES_DBNAME"
    AASREG_POSTGRES_MAXOPENCONNECTIONS="$BASYX_REPO_POSTGRES_MAXOPENCONNECTIONS"
    AASREG_POSTGRES_MAXIDLECONNECTIONS="$BASYX_REPO_POSTGRES_MAXIDLECONNECTIONS"
    AASREG_POSTGRES_CONNMAXLIFETIMEMINUTES="$BASYX_REPO_POSTGRES_CONNMAXLIFETIMEMINUTES"
    AASREG_ABAC_ENABLED="$BASYX_REPO_ABAC_ENABLED"
    AASREG_ABAC_MODELPATH="$BASYX_REPO_ABAC_MODELPATH"
    AASREG_OIDC_TRUSTLISTPATH="$BASYX_REPO_OIDC_TRUSTLISTPATH"
    SMREG_CORS_ALLOWEDORIGINS="$BASYX_REPO_CORS_ALLOWEDORIGINS"
    SMREG_CORS_ALLOWEDHEADERS="$BASYX_REPO_CORS_ALLOWEDHEADERS"
    SMREG_CORS_ALLOWEDCREDENTIALS="$BASYX_REPO_CORS_ALLOWEDCREDENTIALS"
    SMREG_CORS_ALLOWEDMETHODS="$BASYX_REPO_CORS_ALLOWEDMETHODS"
    SMREG_POSTGRES_HOST="$BASYX_REPO_POSTGRES_HOST"
    SMREG_POSTGRES_PORT="$BASYX_REPO_POSTGRES_PORT"
    SMREG_POSTGRES_USER="$BASYX_REPO_POSTGRES_USER"
    SMREG_POSTGRES_PASSWORD="$BASYX_REPO_POSTGRES_PASSWORD"
    SMREG_POSTGRES_DBNAME="$BASYX_REPO_POSTGRES_DBNAME"
    SMREG_POSTGRES_MAXOPENCONNECTIONS="$BASYX_REPO_POSTGRES_MAXOPENCONNECTIONS"
    SMREG_POSTGRES_MAXIDLECONNECTIONS="$BASYX_REPO_POSTGRES_MAXIDLECONNECTIONS"
    SMREG_POSTGRES_CONNMAXLIFETIMEMINUTES="$BASYX_REPO_POSTGRES_CONNMAXLIFETIMEMINUTES"
    SMREG_ABAC_ENABLED="$BASYX_REPO_ABAC_ENABLED"
    SMREG_ABAC_MODELPATH="$BASYX_REPO_ABAC_MODELPATH"
    SMREG_OIDC_TRUSTLISTPATH="$BASYX_REPO_OIDC_TRUSTLISTPATH"
    AASDISC_CORS_ALLOWEDORIGINS="$BASYX_REPO_CORS_ALLOWEDORIGINS"
    AASDISC_CORS_ALLOWEDHEADERS="$BASYX_REPO_CORS_ALLOWEDHEADERS"
    AASDISC_CORS_ALLOWEDCREDENTIALS="$BASYX_REPO_CORS_ALLOWEDCREDENTIALS"
    AASDISC_CORS_ALLOWEDMETHODS="$BASYX_REPO_CORS_ALLOWEDMETHODS"
    AASDISC_POSTGRES_HOST="$BASYX_REPO_POSTGRES_HOST"
    AASDISC_POSTGRES_PORT="$BASYX_REPO_POSTGRES_PORT"
    AASDISC_POSTGRES_USER="$BASYX_REPO_POSTGRES_USER"
    AASDISC_POSTGRES_PASSWORD="$BASYX_REPO_POSTGRES_PASSWORD"
    AASDISC_POSTGRES_DBNAME="$BASYX_REPO_POSTGRES_DBNAME"
    AASDISC_POSTGRES_MAXOPENCONNECTIONS="$BASYX_REPO_POSTGRES_MAXOPENCONNECTIONS"
    AASDISC_POSTGRES_MAXIDLECONNECTIONS="$BASYX_REPO_POSTGRES_MAXIDLECONNECTIONS"
    AASDISC_POSTGRES_CONNMAXLIFETIMEMINUTES="$BASYX_REPO_POSTGRES_CONNMAXLIFETIMEMINUTES"
    AASDISC_ABAC_ENABLED="$BASYX_REPO_ABAC_ENABLED"
    AASDISC_ABAC_MODELPATH="$BASYX_REPO_ABAC_MODELPATH"
    AASDISC_OIDC_TRUSTLISTPATH="$BASYX_REPO_OIDC_TRUSTLISTPATH"

    BASYX_AAS_REGISTRY_CONTAINER="${PROJECT_NAME}-aasregistry-go"
    BASYX_AAS_REGISTRY_CONTAINER_PORT="${AASREG_SERVER_PORT}"
    BASYX_AAS_REGISTRY_URL="http://${BASYX_AAS_REGISTRY_CONTAINER}:${BASYX_AAS_REGISTRY_CONTAINER_PORT}"
    BASYX_AAS_REGISTRY_HC_URL="${BASYX_AAS_REGISTRY_URL}/health"
    BASYX_SUBMODEL_REGISTRY_CONTAINER="${PROJECT_NAME}-submodelregistry-go"
    BASYX_SUBMODEL_REGISTRY_CONTAINER_PORT="${SMREG_SERVER_PORT}"
    BASYX_SUBMODEL_REGISTRY_URL="http://${BASYX_SUBMODEL_REGISTRY_CONTAINER}:${BASYX_SUBMODEL_REGISTRY_CONTAINER_PORT}"
    BASYX_SUBMODEL_REGISTRY_HC_URL="${BASYX_SUBMODEL_REGISTRY_URL}/health"
    BASYX_AAS_DISCOVERY_CONTAINER="${PROJECT_NAME}-aasdiscovery-go"
    BASYX_AAS_DISCOVERY_CONTAINER_PORT="${AASDISC_SERVER_PORT}"
    BASYX_AAS_DISCOVERY_URL="http://${BASYX_AAS_DISCOVERY_CONTAINER}:${BASYX_AAS_DISCOVERY_CONTAINER_PORT}"
    BASYX_AAS_DISCOVERY_HC_URL="${BASYX_AAS_DISCOVERY_URL}/health"
  fi

  local ports=()
  ports+=("$GATEWAY_HOST_PORT")
  if [ "$KEYCLOAK_MODE" = "install" ]; then
    ports+=("$KEYCLOAK_HOST_PORT")
  fi
  if [ "$BASYX_MODE" = "install" ]; then
    ports+=("$AAS_REPOSITORY_HOST_PORT" "$SUBMODEL_REPOSITORY_HOST_PORT" "$CONCEPT_DESCRIPTION_REPOSITORY_HOST_PORT" "$AAS_REGISTRY_HOST_PORT" "$SUBMODEL_REGISTRY_HOST_PORT" "$AAS_DISCOVERY_HOST_PORT")
  fi
  assert_unique_ports "${ports[@]}"

  init_output_files "$COMPOSE_FILE" "$ENV_FILE"
  if [ "$KEYCLOAK_MODE" = "install" ]; then
    prepare_keycloak_assets "$COMPOSE_FILE" "$resolved_keycloak_realm_file" "$resolved_keycloak_themes_path" "$PUBLIC_GATEWAY_URL"
  fi
  if [ "$BASYX_MODE" = "install" ]; then
    prepare_security_env_assets "$COMPOSE_FILE"
  fi

  write_env "$ENV_FILE" "PROJECT_NAME" "$PROJECT_NAME"
  write_env "$ENV_FILE" "DESIGNER_BACKEND_IMAGE_REPO" "$DESIGNER_BACKEND_IMAGE_REPO"
  write_env "$ENV_FILE" "DESIGNER_BACKEND_IMAGE_TAG" "$DESIGNER_BACKEND_IMAGE_TAG"
  write_env "$ENV_FILE" "GATEWAY_IMAGE_REPO" "$GATEWAY_IMAGE_REPO"
  write_env "$ENV_FILE" "GATEWAY_IMAGE_TAG" "$GATEWAY_IMAGE_TAG"
  write_env "$ENV_FILE" "FRONTEND_IMAGE_REPO" "$FRONTEND_IMAGE_REPO"
  write_env "$ENV_FILE" "FRONTEND_IMAGE_TAG" "$FRONTEND_IMAGE_TAG"
  write_env "$ENV_FILE" "BASE_URL" "$BASE_URL"
  write_env "$ENV_FILE" "FRONTEND_API_BASE_URL" "$FRONTEND_API_BASE_URL"
  write_env "$ENV_FILE" "FRONTEND_FEEDMAPPING_BASE_URL" "$FRONTEND_FEEDMAPPING_BASE_URL"
  write_env "$ENV_FILE" "POSTGRES_IMAGE_REPO" "$POSTGRES_IMAGE_REPO"
  write_env "$ENV_FILE" "POSTGRES_IMAGE_TAG" "$POSTGRES_IMAGE_TAG"
  write_env "$ENV_FILE" "POSTGRES_DB" "$POSTGRES_DB"
  write_env "$ENV_FILE" "POSTGRES_USER" "$POSTGRES_USER"
  write_env "$ENV_FILE" "POSTGRES_PASSWORD" "$POSTGRES_PASSWORD"
  write_env "$ENV_FILE" "BASYX_POSTGRES_DB" "$BASYX_POSTGRES_DB"
  write_env "$ENV_FILE" "KEYCLOAK_POSTGRES_DB" "$KEYCLOAK_POSTGRES_DB"
  write_env "$ENV_FILE" "BASYX_MODE" "$BASYX_MODE"
  write_env "$ENV_FILE" "KEYCLOAK_MODE" "$KEYCLOAK_MODE"

  write_env "$ENV_FILE" "KEYCLOAK_ISSUER" "$KEYCLOAK_ISSUER"
  write_env "$ENV_FILE" "KEYCLOAK_WELLKNOWN_URL" "$KEYCLOAK_WELLKNOWN_URL"
  write_env "$ENV_FILE" "KEYCLOAK_PUBLIC_ISSUER" "$KEYCLOAK_PUBLIC_ISSUER"
  write_env "$ENV_FILE" "KEYCLOAK_PUBLIC_WELLKNOWN_URL" "$KEYCLOAK_PUBLIC_WELLKNOWN_URL"
  write_env "$ENV_FILE" "KEYCLOAK_CLIENT_ID" "$KEYCLOAK_CLIENT_ID"
  write_env "$ENV_FILE" "KEYCLOAK_AUDIENCE" "$KEYCLOAK_AUDIENCE"
  write_env "$ENV_FILE" "KEYCLOAK_SCOPES" "$KEYCLOAK_SCOPES"
  write_env "$ENV_FILE" "KEYCLOAK_RESOURCE_ACCESS_NAME" "$KEYCLOAK_RESOURCE_ACCESS_NAME"
  write_env "$ENV_FILE" "KEYCLOAK_ADMIN_REALM" "$KEYCLOAK_ADMIN_REALM"
  write_env "$ENV_FILE" "KEYCLOAK_ADMIN_CLIENT_ID" "$KEYCLOAK_ADMIN_CLIENT_ID"
  write_env "$ENV_FILE" "KEYCLOAK_ADMIN_CLIENT_SECRET" "$KEYCLOAK_ADMIN_CLIENT_SECRET"
  write_env "$ENV_FILE" "KEYCLOAK_ADMIN_USERNAME" "$KEYCLOAK_ADMIN_USERNAME"
  write_env "$ENV_FILE" "KEYCLOAK_ADMIN_PASSWORD" "$KEYCLOAK_ADMIN_PASSWORD"
  write_env "$ENV_FILE" "INITIAL_ORGANISATION_ADMIN_EMAIL" "$INITIAL_ORGANISATION_ADMIN_EMAIL"
  write_env "$ENV_FILE" "INITIAL_ORGANISATION_ADMIN_NAME" "$INITIAL_ORGANISATION_ADMIN_NAME"
  write_env "$ENV_FILE" "INITIAL_ORGANISATION_ADMIN_VORNAME" "$INITIAL_ORGANISATION_ADMIN_VORNAME"
  write_env "$ENV_FILE" "INITIAL_ORGANISATION_ADMIN_PASSWORD" "$INITIAL_ORGANISATION_ADMIN_PASSWORD"
  write_env "$ENV_FILE" "SMTP_SERVER" "$SMTP_SERVER"
  write_env "$ENV_FILE" "SMTP_PORT" "$SMTP_PORT"
  write_env "$ENV_FILE" "SMTP_USE_SSL" "$SMTP_USE_SSL"
  write_env "$ENV_FILE" "SMTP_USE_TLS" "$SMTP_USE_TLS"
  write_env "$ENV_FILE" "SMTP_NEEDS_AUTHENTICATION" "$SMTP_NEEDS_AUTHENTICATION"
  write_env "$ENV_FILE" "SENDER_ADDRESS" "$SENDER_ADDRESS"
  write_env "$ENV_FILE" "SENDER_USER" "$SENDER_USER"
  write_env "$ENV_FILE" "SENDER_PASSWORD" "$SENDER_PASSWORD"
  write_env "$ENV_FILE" "NEW_ORGA_NOTIFICATION_ADDRESS" "$NEW_ORGA_NOTIFICATION_ADDRESS"
  write_env "$ENV_FILE" "SUBJECT_PREFIX" "$SUBJECT_PREFIX"

  write_env "$ENV_FILE" "BASYX_AAS_REPOSITORY_URL" "$BASYX_AAS_REPOSITORY_URL"
  write_env "$ENV_FILE" "BASYX_SUBMODEL_REPOSITORY_URL" "$BASYX_SUBMODEL_REPOSITORY_URL"
  write_env "$ENV_FILE" "BASYX_CONCEPT_DESCRIPTION_REPOSITORY_URL" "$BASYX_CONCEPT_DESCRIPTION_REPOSITORY_URL"
  write_env "$ENV_FILE" "BASYX_AAS_REGISTRY_URL" "$BASYX_AAS_REGISTRY_URL"
  write_env "$ENV_FILE" "BASYX_SUBMODEL_REGISTRY_URL" "$BASYX_SUBMODEL_REGISTRY_URL"
  write_env "$ENV_FILE" "BASYX_AAS_DISCOVERY_URL" "$BASYX_AAS_DISCOVERY_URL"
  write_env "$ENV_FILE" "AAS_REPOSITORY_IMAGE_TAG" "$AAS_REPOSITORY_IMAGE_TAG"
  write_env "$ENV_FILE" "SUBMODEL_REPOSITORY_IMAGE_TAG" "$SUBMODEL_REPOSITORY_IMAGE_TAG"
  write_env "$ENV_FILE" "CONCEPT_DESCRIPTION_REPOSITORY_IMAGE_TAG" "$CONCEPT_DESCRIPTION_REPOSITORY_IMAGE_TAG"
  write_env "$ENV_FILE" "AAS_REGISTRY_IMAGE_TAG" "$AAS_REGISTRY_IMAGE_TAG"
  write_env "$ENV_FILE" "SUBMODEL_REGISTRY_IMAGE_TAG" "$SUBMODEL_REGISTRY_IMAGE_TAG"
  write_env "$ENV_FILE" "AAS_DISCOVERY_IMAGE_TAG" "$AAS_DISCOVERY_IMAGE_TAG"
  write_env "$ENV_FILE" "BASYX_HANDLE_AS_INTERNAL" "$BASYX_HANDLE_AS_INTERNAL"
  write_env "$ENV_FILE" "BASYX_AAS_REPOSITORY_CONTAINER" "$BASYX_AAS_REPOSITORY_CONTAINER"
  write_env "$ENV_FILE" "BASYX_AAS_REPOSITORY_CONTAINER_PORT" "$BASYX_AAS_REPOSITORY_CONTAINER_PORT"
  write_env "$ENV_FILE" "BASYX_AAS_REPOSITORY_HC_URL" "$BASYX_AAS_REPOSITORY_HC_URL"
  write_env "$ENV_FILE" "BASYX_SUBMODEL_REPOSITORY_CONTAINER" "$BASYX_SUBMODEL_REPOSITORY_CONTAINER"
  write_env "$ENV_FILE" "BASYX_SUBMODEL_REPOSITORY_CONTAINER_PORT" "$BASYX_SUBMODEL_REPOSITORY_CONTAINER_PORT"
  write_env "$ENV_FILE" "BASYX_SUBMODEL_REPOSITORY_HC_URL" "$BASYX_SUBMODEL_REPOSITORY_HC_URL"
  write_env "$ENV_FILE" "BASYX_CONCEPT_DESCRIPTION_REPOSITORY_CONTAINER" "$BASYX_CONCEPT_DESCRIPTION_REPOSITORY_CONTAINER"
  write_env "$ENV_FILE" "BASYX_CONCEPT_DESCRIPTION_REPOSITORY_CONTAINER_PORT" "$BASYX_CONCEPT_DESCRIPTION_REPOSITORY_CONTAINER_PORT"
  write_env "$ENV_FILE" "BASYX_CONCEPT_DESCRIPTION_REPOSITORY_HC_URL" "$BASYX_CONCEPT_DESCRIPTION_REPOSITORY_HC_URL"
  write_env "$ENV_FILE" "BASYX_AAS_REGISTRY_CONTAINER" "$BASYX_AAS_REGISTRY_CONTAINER"
  write_env "$ENV_FILE" "BASYX_AAS_REGISTRY_CONTAINER_PORT" "$BASYX_AAS_REGISTRY_CONTAINER_PORT"
  write_env "$ENV_FILE" "BASYX_AAS_REGISTRY_HC_URL" "$BASYX_AAS_REGISTRY_HC_URL"
  write_env "$ENV_FILE" "BASYX_SUBMODEL_REGISTRY_CONTAINER" "$BASYX_SUBMODEL_REGISTRY_CONTAINER"
  write_env "$ENV_FILE" "BASYX_SUBMODEL_REGISTRY_CONTAINER_PORT" "$BASYX_SUBMODEL_REGISTRY_CONTAINER_PORT"
  write_env "$ENV_FILE" "BASYX_SUBMODEL_REGISTRY_HC_URL" "$BASYX_SUBMODEL_REGISTRY_HC_URL"
  write_env "$ENV_FILE" "BASYX_AAS_DISCOVERY_CONTAINER" "$BASYX_AAS_DISCOVERY_CONTAINER"
  write_env "$ENV_FILE" "BASYX_AAS_DISCOVERY_CONTAINER_PORT" "$BASYX_AAS_DISCOVERY_CONTAINER_PORT"
  write_env "$ENV_FILE" "BASYX_AAS_DISCOVERY_HC_URL" "$BASYX_AAS_DISCOVERY_HC_URL"
  write_env "$ENV_FILE" "AASREPO_CORS_ALLOWEDORIGINS" "$AASREPO_CORS_ALLOWEDORIGINS"
  write_env "$ENV_FILE" "AASREPO_CORS_ALLOWEDHEADERS" "$AASREPO_CORS_ALLOWEDHEADERS"
  write_env "$ENV_FILE" "AASREPO_CORS_ALLOWEDCREDENTIALS" "$AASREPO_CORS_ALLOWEDCREDENTIALS"
  write_env "$ENV_FILE" "AASREPO_CORS_ALLOWEDMETHODS" "$AASREPO_CORS_ALLOWEDMETHODS"
  write_env "$ENV_FILE" "AASREPO_SERVER_PORT" "$AASREPO_SERVER_PORT"
  write_env "$ENV_FILE" "AASREPO_POSTGRES_HOST" "$AASREPO_POSTGRES_HOST"
  write_env "$ENV_FILE" "AASREPO_POSTGRES_PORT" "$AASREPO_POSTGRES_PORT"
  write_env "$ENV_FILE" "AASREPO_POSTGRES_USER" "$AASREPO_POSTGRES_USER"
  write_env "$ENV_FILE" "AASREPO_POSTGRES_PASSWORD" "$AASREPO_POSTGRES_PASSWORD"
  write_env "$ENV_FILE" "AASREPO_POSTGRES_DBNAME" "$AASREPO_POSTGRES_DBNAME"
  write_env "$ENV_FILE" "AASREPO_POSTGRES_MAXOPENCONNECTIONS" "$AASREPO_POSTGRES_MAXOPENCONNECTIONS"
  write_env "$ENV_FILE" "AASREPO_POSTGRES_MAXIDLECONNECTIONS" "$AASREPO_POSTGRES_MAXIDLECONNECTIONS"
  write_env "$ENV_FILE" "AASREPO_POSTGRES_CONNMAXLIFETIMEMINUTES" "$AASREPO_POSTGRES_CONNMAXLIFETIMEMINUTES"
  write_env "$ENV_FILE" "AASREPO_ABAC_ENABLED" "$AASREPO_ABAC_ENABLED"
  write_env "$ENV_FILE" "AASREPO_ABAC_MODELPATH" "$AASREPO_ABAC_MODELPATH"
  write_env "$ENV_FILE" "AASREPO_OIDC_TRUSTLISTPATH" "$AASREPO_OIDC_TRUSTLISTPATH"
  write_env "$ENV_FILE" "SMREPO_CORS_ALLOWEDORIGINS" "$SMREPO_CORS_ALLOWEDORIGINS"
  write_env "$ENV_FILE" "SMREPO_CORS_ALLOWEDHEADERS" "$SMREPO_CORS_ALLOWEDHEADERS"
  write_env "$ENV_FILE" "SMREPO_CORS_ALLOWEDCREDENTIALS" "$SMREPO_CORS_ALLOWEDCREDENTIALS"
  write_env "$ENV_FILE" "SMREPO_CORS_ALLOWEDMETHODS" "$SMREPO_CORS_ALLOWEDMETHODS"
  write_env "$ENV_FILE" "SMREPO_SERVER_PORT" "$SMREPO_SERVER_PORT"
  write_env "$ENV_FILE" "SMREPO_POSTGRES_HOST" "$SMREPO_POSTGRES_HOST"
  write_env "$ENV_FILE" "SMREPO_POSTGRES_PORT" "$SMREPO_POSTGRES_PORT"
  write_env "$ENV_FILE" "SMREPO_POSTGRES_USER" "$SMREPO_POSTGRES_USER"
  write_env "$ENV_FILE" "SMREPO_POSTGRES_PASSWORD" "$SMREPO_POSTGRES_PASSWORD"
  write_env "$ENV_FILE" "SMREPO_POSTGRES_DBNAME" "$SMREPO_POSTGRES_DBNAME"
  write_env "$ENV_FILE" "SMREPO_POSTGRES_MAXOPENCONNECTIONS" "$SMREPO_POSTGRES_MAXOPENCONNECTIONS"
  write_env "$ENV_FILE" "SMREPO_POSTGRES_MAXIDLECONNECTIONS" "$SMREPO_POSTGRES_MAXIDLECONNECTIONS"
  write_env "$ENV_FILE" "SMREPO_POSTGRES_CONNMAXLIFETIMEMINUTES" "$SMREPO_POSTGRES_CONNMAXLIFETIMEMINUTES"
  write_env "$ENV_FILE" "SMREPO_ABAC_ENABLED" "$SMREPO_ABAC_ENABLED"
  write_env "$ENV_FILE" "SMREPO_ABAC_MODELPATH" "$SMREPO_ABAC_MODELPATH"
  write_env "$ENV_FILE" "SMREPO_OIDC_TRUSTLISTPATH" "$SMREPO_OIDC_TRUSTLISTPATH"
  write_env "$ENV_FILE" "SMREPO_JWS_PRIVATEKEYPATH" "$SMREPO_JWS_PRIVATEKEYPATH"
  write_env "$ENV_FILE" "CDREPO_CORS_ALLOWEDORIGINS" "$CDREPO_CORS_ALLOWEDORIGINS"
  write_env "$ENV_FILE" "CDREPO_CORS_ALLOWEDHEADERS" "$CDREPO_CORS_ALLOWEDHEADERS"
  write_env "$ENV_FILE" "CDREPO_CORS_ALLOWEDCREDENTIALS" "$CDREPO_CORS_ALLOWEDCREDENTIALS"
  write_env "$ENV_FILE" "CDREPO_CORS_ALLOWEDMETHODS" "$CDREPO_CORS_ALLOWEDMETHODS"
  write_env "$ENV_FILE" "CDREPO_SERVER_PORT" "$CDREPO_SERVER_PORT"
  write_env "$ENV_FILE" "CDREPO_POSTGRES_HOST" "$CDREPO_POSTGRES_HOST"
  write_env "$ENV_FILE" "CDREPO_POSTGRES_PORT" "$CDREPO_POSTGRES_PORT"
  write_env "$ENV_FILE" "CDREPO_POSTGRES_USER" "$CDREPO_POSTGRES_USER"
  write_env "$ENV_FILE" "CDREPO_POSTGRES_PASSWORD" "$CDREPO_POSTGRES_PASSWORD"
  write_env "$ENV_FILE" "CDREPO_POSTGRES_DBNAME" "$CDREPO_POSTGRES_DBNAME"
  write_env "$ENV_FILE" "CDREPO_POSTGRES_MAXOPENCONNECTIONS" "$CDREPO_POSTGRES_MAXOPENCONNECTIONS"
  write_env "$ENV_FILE" "CDREPO_POSTGRES_MAXIDLECONNECTIONS" "$CDREPO_POSTGRES_MAXIDLECONNECTIONS"
  write_env "$ENV_FILE" "CDREPO_POSTGRES_CONNMAXLIFETIMEMINUTES" "$CDREPO_POSTGRES_CONNMAXLIFETIMEMINUTES"
  write_env "$ENV_FILE" "CDREPO_ABAC_ENABLED" "$CDREPO_ABAC_ENABLED"
  write_env "$ENV_FILE" "CDREPO_ABAC_MODELPATH" "$CDREPO_ABAC_MODELPATH"
  write_env "$ENV_FILE" "CDREPO_OIDC_TRUSTLISTPATH" "$CDREPO_OIDC_TRUSTLISTPATH"
  write_env "$ENV_FILE" "AASREG_CORS_ALLOWEDORIGINS" "$AASREG_CORS_ALLOWEDORIGINS"
  write_env "$ENV_FILE" "AASREG_CORS_ALLOWEDHEADERS" "$AASREG_CORS_ALLOWEDHEADERS"
  write_env "$ENV_FILE" "AASREG_CORS_ALLOWEDCREDENTIALS" "$AASREG_CORS_ALLOWEDCREDENTIALS"
  write_env "$ENV_FILE" "AASREG_CORS_ALLOWEDMETHODS" "$AASREG_CORS_ALLOWEDMETHODS"
  write_env "$ENV_FILE" "AASREG_VIRTUAL_PORT" "$AASREG_VIRTUAL_PORT"
  write_env "$ENV_FILE" "AASREG_SERVER_PORT" "$AASREG_SERVER_PORT"
  write_env "$ENV_FILE" "AASREG_POSTGRES_HOST" "$AASREG_POSTGRES_HOST"
  write_env "$ENV_FILE" "AASREG_POSTGRES_PORT" "$AASREG_POSTGRES_PORT"
  write_env "$ENV_FILE" "AASREG_POSTGRES_USER" "$AASREG_POSTGRES_USER"
  write_env "$ENV_FILE" "AASREG_POSTGRES_PASSWORD" "$AASREG_POSTGRES_PASSWORD"
  write_env "$ENV_FILE" "AASREG_POSTGRES_DBNAME" "$AASREG_POSTGRES_DBNAME"
  write_env "$ENV_FILE" "AASREG_POSTGRES_MAXOPENCONNECTIONS" "$AASREG_POSTGRES_MAXOPENCONNECTIONS"
  write_env "$ENV_FILE" "AASREG_POSTGRES_MAXIDLECONNECTIONS" "$AASREG_POSTGRES_MAXIDLECONNECTIONS"
  write_env "$ENV_FILE" "AASREG_POSTGRES_CONNMAXLIFETIMEMINUTES" "$AASREG_POSTGRES_CONNMAXLIFETIMEMINUTES"
  write_env "$ENV_FILE" "AASREG_ABAC_ENABLED" "$AASREG_ABAC_ENABLED"
  write_env "$ENV_FILE" "AASREG_ABAC_MODELPATH" "$AASREG_ABAC_MODELPATH"
  write_env "$ENV_FILE" "AASREG_OIDC_TRUSTLISTPATH" "$AASREG_OIDC_TRUSTLISTPATH"
  write_env "$ENV_FILE" "SMREG_CORS_ALLOWEDORIGINS" "$SMREG_CORS_ALLOWEDORIGINS"
  write_env "$ENV_FILE" "SMREG_CORS_ALLOWEDHEADERS" "$SMREG_CORS_ALLOWEDHEADERS"
  write_env "$ENV_FILE" "SMREG_CORS_ALLOWEDCREDENTIALS" "$SMREG_CORS_ALLOWEDCREDENTIALS"
  write_env "$ENV_FILE" "SMREG_CORS_ALLOWEDMETHODS" "$SMREG_CORS_ALLOWEDMETHODS"
  write_env "$ENV_FILE" "SMREG_VIRTUAL_PORT" "$SMREG_VIRTUAL_PORT"
  write_env "$ENV_FILE" "SMREG_SERVER_PORT" "$SMREG_SERVER_PORT"
  write_env "$ENV_FILE" "SMREG_POSTGRES_HOST" "$SMREG_POSTGRES_HOST"
  write_env "$ENV_FILE" "SMREG_POSTGRES_PORT" "$SMREG_POSTGRES_PORT"
  write_env "$ENV_FILE" "SMREG_POSTGRES_USER" "$SMREG_POSTGRES_USER"
  write_env "$ENV_FILE" "SMREG_POSTGRES_PASSWORD" "$SMREG_POSTGRES_PASSWORD"
  write_env "$ENV_FILE" "SMREG_POSTGRES_DBNAME" "$SMREG_POSTGRES_DBNAME"
  write_env "$ENV_FILE" "SMREG_POSTGRES_MAXOPENCONNECTIONS" "$SMREG_POSTGRES_MAXOPENCONNECTIONS"
  write_env "$ENV_FILE" "SMREG_POSTGRES_MAXIDLECONNECTIONS" "$SMREG_POSTGRES_MAXIDLECONNECTIONS"
  write_env "$ENV_FILE" "SMREG_POSTGRES_CONNMAXLIFETIMEMINUTES" "$SMREG_POSTGRES_CONNMAXLIFETIMEMINUTES"
  write_env "$ENV_FILE" "SMREG_ABAC_ENABLED" "$SMREG_ABAC_ENABLED"
  write_env "$ENV_FILE" "SMREG_ABAC_MODELPATH" "$SMREG_ABAC_MODELPATH"
  write_env "$ENV_FILE" "SMREG_OIDC_TRUSTLISTPATH" "$SMREG_OIDC_TRUSTLISTPATH"
  write_env "$ENV_FILE" "AASDISC_CORS_ALLOWEDORIGINS" "$AASDISC_CORS_ALLOWEDORIGINS"
  write_env "$ENV_FILE" "AASDISC_CORS_ALLOWEDHEADERS" "$AASDISC_CORS_ALLOWEDHEADERS"
  write_env "$ENV_FILE" "AASDISC_CORS_ALLOWEDCREDENTIALS" "$AASDISC_CORS_ALLOWEDCREDENTIALS"
  write_env "$ENV_FILE" "AASDISC_CORS_ALLOWEDMETHODS" "$AASDISC_CORS_ALLOWEDMETHODS"
  write_env "$ENV_FILE" "AASDISC_VIRTUAL_PORT" "$AASDISC_VIRTUAL_PORT"
  write_env "$ENV_FILE" "AASDISC_SERVER_PORT" "$AASDISC_SERVER_PORT"
  write_env "$ENV_FILE" "AASDISC_POSTGRES_HOST" "$AASDISC_POSTGRES_HOST"
  write_env "$ENV_FILE" "AASDISC_POSTGRES_PORT" "$AASDISC_POSTGRES_PORT"
  write_env "$ENV_FILE" "AASDISC_POSTGRES_USER" "$AASDISC_POSTGRES_USER"
  write_env "$ENV_FILE" "AASDISC_POSTGRES_PASSWORD" "$AASDISC_POSTGRES_PASSWORD"
  write_env "$ENV_FILE" "AASDISC_POSTGRES_DBNAME" "$AASDISC_POSTGRES_DBNAME"
  write_env "$ENV_FILE" "AASDISC_POSTGRES_MAXOPENCONNECTIONS" "$AASDISC_POSTGRES_MAXOPENCONNECTIONS"
  write_env "$ENV_FILE" "AASDISC_POSTGRES_MAXIDLECONNECTIONS" "$AASDISC_POSTGRES_MAXIDLECONNECTIONS"
  write_env "$ENV_FILE" "AASDISC_POSTGRES_CONNMAXLIFETIMEMINUTES" "$AASDISC_POSTGRES_CONNMAXLIFETIMEMINUTES"
  write_env "$ENV_FILE" "AASDISC_ABAC_ENABLED" "$AASDISC_ABAC_ENABLED"
  write_env "$ENV_FILE" "AASDISC_ABAC_MODELPATH" "$AASDISC_ABAC_MODELPATH"
  write_env "$ENV_FILE" "AASDISC_OIDC_TRUSTLISTPATH" "$AASDISC_OIDC_TRUSTLISTPATH"

  if [ "$KEYCLOAK_MODE" = "install" ]; then
    write_env "$ENV_FILE" "KEYCLOAK_IMAGE_REPO" "$KEYCLOAK_IMAGE_REPO"
    write_env "$ENV_FILE" "KEYCLOAK_IMAGE_TAG" "$KEYCLOAK_IMAGE_TAG"
    write_env "$ENV_FILE" "KEYCLOAK_REALM_FILE" "./stack-assets/keycloak/aas-local-realm.json"
    write_env "$ENV_FILE" "KEYCLOAK_THEMES_PATH" "./stack-assets/keycloak/themes"
  fi

  if [ "$BASYX_MODE" = "install" ]; then
    write_env "$ENV_FILE" "AAS_REPOSITORY_IMAGE_REPO" "$AAS_REPOSITORY_IMAGE_REPO"
    write_env "$ENV_FILE" "AAS_REPOSITORY_HOST_PORT" "$AAS_REPOSITORY_HOST_PORT"
    write_env "$ENV_FILE" "SUBMODEL_REPOSITORY_IMAGE_REPO" "$SUBMODEL_REPOSITORY_IMAGE_REPO"
    write_env "$ENV_FILE" "SUBMODEL_REPOSITORY_HOST_PORT" "$SUBMODEL_REPOSITORY_HOST_PORT"
    write_env "$ENV_FILE" "CONCEPT_DESCRIPTION_REPOSITORY_IMAGE_REPO" "$CONCEPT_DESCRIPTION_REPOSITORY_IMAGE_REPO"
    write_env "$ENV_FILE" "CONCEPT_DESCRIPTION_REPOSITORY_HOST_PORT" "$CONCEPT_DESCRIPTION_REPOSITORY_HOST_PORT"
    write_env "$ENV_FILE" "AAS_REGISTRY_IMAGE_REPO" "$AAS_REGISTRY_IMAGE_REPO"
    write_env "$ENV_FILE" "AAS_REGISTRY_HOST_PORT" "$AAS_REGISTRY_HOST_PORT"
    write_env "$ENV_FILE" "SUBMODEL_REGISTRY_IMAGE_REPO" "$SUBMODEL_REGISTRY_IMAGE_REPO"
    write_env "$ENV_FILE" "SUBMODEL_REGISTRY_HOST_PORT" "$SUBMODEL_REGISTRY_HOST_PORT"
    write_env "$ENV_FILE" "AAS_DISCOVERY_IMAGE_REPO" "$AAS_DISCOVERY_IMAGE_REPO"
    write_env "$ENV_FILE" "AAS_DISCOVERY_HOST_PORT" "$AAS_DISCOVERY_HOST_PORT"
  fi

  {
    printf '# Generiert durch create-compose-oss.sh\n'
    printf '# Verwenden mit: docker compose --env-file %s -f %s up -d\n\n' "$ENV_FILE" "$COMPOSE_FILE"
  } >> "$COMPOSE_FILE"

  compose_begin "$COMPOSE_FILE"
  prepare_postgres_init_assets "$COMPOSE_FILE"
  append_postgres_service "$COMPOSE_FILE" "$NETWORK_NAME" "$POSTGRES_VOLUME"

  if [ "$KEYCLOAK_MODE" = "install" ]; then
    append_service_separator "$COMPOSE_FILE"
    append_keycloak_internal_service "$COMPOSE_FILE" "$NETWORK_NAME" "$KEYCLOAK_HOST_PORT" "$PUBLIC_GATEWAY_URL"
  fi

  append_service_separator "$COMPOSE_FILE"
  append_gateway_service "$COMPOSE_FILE" "$NETWORK_NAME" "$GATEWAY_HOST_PORT" "$GATEWAY_CONTAINER_PORT" "$KEYCLOAK_CLUSTER_URL" "http://aas-designer-community:${DESIGNER_BACKEND_CONTAINER_PORT}" "http://frontend:${FRONTEND_CONTAINER_PORT}" "false" "$KEYCLOAK_MODE" "aas-designer-community"

  append_service_separator "$COMPOSE_FILE"
  append_designer_backend_service "$COMPOSE_FILE" "$NETWORK_NAME" "$DESIGNER_BACKEND_CONTAINER_PORT" "$GATEWAY_CONTAINER_PORT" "$KEYCLOAK_MODE" "aas-designer-community"

  append_service_separator "$COMPOSE_FILE"
  append_frontend_service "$COMPOSE_FILE" "$NETWORK_NAME" "$FRONTEND_CONTAINER_PORT" "aas-designer-community"

  if [ "$BASYX_MODE" = "install" ]; then
    append_service_separator "$COMPOSE_FILE"
    append_basyx_internal_services "$COMPOSE_FILE" "$NETWORK_NAME"
  fi

  append_networks_block "$COMPOSE_FILE" "$NETWORK_NAME"
  append_volumes_block "$COMPOSE_FILE" "$POSTGRES_VOLUME"

  local RUN_CONFIG_CHECK RUN_STACK_START
  component_header "Startoptionen"
  ask_choice RUN_CONFIG_CHECK "docker compose config ausführen" "yes,no" "$(state_default RUN_CONFIG_CHECK "yes")"
  ask_choice RUN_STACK_START "Stack direkt starten" "yes,no" "$(state_default RUN_STACK_START "yes")"

  run_optional_startup "$COMPOSE_FILE" "$ENV_FILE" "$RUN_CONFIG_CHECK" "$RUN_STACK_START" "$IMAGE_SOURCE" "$PROJECT_NAME"

  persist_state
  trap - EXIT

  info "Fertig."
  info "Compose: $COMPOSE_FILE"
  info "Env: $ENV_FILE"
  info "Defaults gespeichert: $STATE_FILE"
}

main "$@"
